"""
Full authentic recipe seed.
Run after the main dish seed.
Usage: python seed_recipes.py
"""
import asyncio, os
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()
client = AsyncIOMotorClient(os.getenv("MONGO_URL", "mongodb://localhost:27017"))
db = client[os.getenv("DB_NAME", "megeb")]
dishes_col = db["dishes"]
vars_col   = db["recipe_variations"]

NOW = datetime.now(timezone.utc)

def v(dish_id, vname, ing, steps, tags=None, prep=20, cook=40, sv=4, sp="medium", notes="", story=""):
    return {
        "dish_id": str(dish_id),
        "variation_name": vname,
        "author_id": "system",
        "author_name": "Megeb Kitchen",
        "ingredients": ing,
        "steps": [{"title": t, "text": x} for t, x in steps],
        "image_url": "",
        "prep_time_minutes": prep,
        "cook_time_minutes": cook,
        "servings": sv,
        "spice_level": sp,
        "notes": notes,
        "dietary_tags": tags or [],
        "story": story,
        "status": "approved",
        "likes_count": 0,
        "search_count": 0,
        "created_at": NOW,
    }

# Full authentic recipes keyed by dish name
RECIPES = {}


# ── Stews & Wats ─────────────────────────────────────────────────────────────

RECIPES["Doro Wat"] = lambda did: v(did, "Classic Doro Wat",
    ["1 whole chicken (1.5 kg), cut into 8–10 pieces",
     "4 large red onions, very finely chopped",
     "4 tbsp niter kibbeh (spiced clarified butter)",
     "4 tbsp berbere spice blend",
     "1 tbsp garlic paste",
     "1 tsp ginger paste",
     "4 hard-boiled eggs, peeled and pierced all over with a fork",
     "1 tsp black cardamom (optional)",
     "Salt to taste",
     "Fresh injera to serve"],
    [("Dry-cook the onions",
      "Place the finely chopped onions in a wide, heavy-bottomed pot over medium heat with NO oil. Stir constantly for 15–20 minutes until they are completely soft, dry, and starting to turn golden. This step is crucial — it builds the sweet, deep base of the wat."),
     ("Add niter kibbeh",
      "Add the niter kibbeh to the dry-cooked onions. Stir well and cook for another 8–10 minutes until the onions are deeply golden and fragrant."),
     ("Add berbere and garlic",
      "Add the berbere spice blend, garlic paste, and ginger paste. Stir continuously for 5–7 minutes. The berbere should darken and become very fragrant. If it starts to stick, add 2–3 tbsp of water."),
     ("Brown the chicken",
      "Add the chicken pieces and turn them to coat every surface in the berbere sauce. Cook uncovered for 10 minutes, turning occasionally."),
     ("Simmer",
      "Add 1/2 cup of water, reduce heat to low, cover and simmer for 30–35 minutes until the chicken is fully cooked and the sauce is very thick. Stir every 10 minutes to prevent sticking."),
     ("Add the eggs",
      "Add the pierced hard-boiled eggs. Gently push them into the sauce. Simmer uncovered for a further 15 minutes so the eggs absorb the sauce colour and flavour."),
     ("Season and serve",
      "Taste and adjust salt. The sauce should be thick, glossy, and deeply red. Serve hot on a bed of fresh injera.")],
    sp="hot", prep=30, cook=90, sv=4,
    story="Doro Wat is Ethiopia's most celebrated dish, served at every wedding, holiday, and significant gathering. The key to its depth is the long dry-cooking of the onions — a technique unique to Ethiopian cuisine.",
    notes="The eggs must be pierced so they absorb the sauce. Do not rush the onion stage — it can take up to 20 minutes.")

RECIPES["Siga Wat"] = lambda did: v(did, "Classic Siga Wat",
    ["700g beef chuck or shoulder, cut into 3cm cubes",
     "4 large red onions, very finely chopped",
     "3 tbsp niter kibbeh",
     "3 tbsp berbere spice blend",
     "1 tbsp garlic paste",
     "1 tsp ginger paste",
     "1/2 cup water",
     "Salt to taste",
     "Injera to serve"],
    [("Dry-cook onions", "Cook onions in a dry heavy pot over medium heat, stirring constantly for 15 min until soft and golden."),
     ("Add niter kibbeh", "Add spiced butter and cook onions a further 8 min until deeply golden."),
     ("Add berbere", "Add berbere, garlic, and ginger. Stir constantly for 6–8 min until dark and fragrant. Add water if it sticks."),
     ("Sear beef", "Add beef cubes and toss to coat fully in the spice paste. Cook uncovered 10 min, stirring often."),
     ("Braise", "Add 1/2 cup water, cover tightly, reduce heat to low. Simmer 45 min until beef is very tender and sauce is thick. Stir every 15 min."),
     ("Finish", "Remove lid and cook a further 5 min to thicken sauce. Season with salt. Serve on injera.")],
    sp="hot", prep=20, cook=70, sv=4,
    story="Siga Wat is the beef version of Ethiopia's beloved spiced stew. It is a centrepiece dish at celebrations and family gatherings.")

RECIPES["Misir Wat"] = lambda did: v(did, "Classic Misir Wat",
    ["2 cups red split lentils, rinsed",
     "3 large red onions, very finely chopped",
     "3 tbsp berbere spice blend",
     "3 tbsp vegetable oil (or niter kibbeh)",
     "1 tbsp garlic paste",
     "1 tsp ginger paste",
     "4 cups water",
     "Salt to taste",
     "Injera to serve"],
    [("Dry-cook onions", "Cook onions in dry pot over medium heat, stirring 10 min until soft. Add oil and cook another 5 min."),
     ("Add spices", "Add berbere, garlic paste, and ginger paste. Cook stirring for 5–6 min until very fragrant and darkened."),
     ("Add lentils and water", "Add rinsed lentils and 4 cups of water. Stir well, bring to a boil."),
     ("Simmer", "Reduce heat to low, cook uncovered for 25–30 min, stirring regularly as the lentils thicken. Add a splash of water if too thick too soon."),
     ("Finish", "When lentils are completely dissolved into a thick, creamy stew, adjust salt. Serve mounded on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="hot", prep=10, cook=40, sv=4,
    story="Misir Wat is a fasting staple eaten throughout Ethiopia during the many Orthodox Christian fasting days, which can total over 200 days a year.")

RECIPES["Shiro Wat"] = lambda did: v(did, "Classic Shiro Wat",
    ["1 cup shiro powder (finely ground spiced chickpea flour)",
     "2 large red onions, very finely chopped",
     "3 cups water",
     "3 tbsp vegetable oil or niter kibbeh",
     "1 tbsp garlic paste",
     "1 tbsp berbere",
     "Salt to taste",
     "Injera to serve"],
    [("Cook onions", "Heat oil in a pot, add onions and cook over medium heat for 10–12 min until golden."),
     ("Add garlic and berbere", "Add garlic paste and berbere. Stir and cook 3 min."),
     ("Add water", "Pour in 3 cups water and bring to a gentle boil while stirring."),
     ("Whisk in shiro", "Slowly pour in the shiro powder in a thin stream while whisking constantly to prevent lumps. Keep whisking for 2 min."),
     ("Simmer and stir", "Reduce heat to low. Cook 12–15 min, stirring constantly — shiro scorches easily. It is ready when thick, smooth, and glossy."),
     ("Serve", "Pour over injera or serve in a clay pot. Top with a drizzle of niter kibbeh.")],
    tags=["vegan", "fasting_friendly"],
    sp="medium", prep=10, cook=25, sv=4,
    notes="Shiro burns easily — never stop stirring once the powder is added.")

RECIPES["Alicha Wat"] = lambda did: v(did, "Classic Alicha Wat",
    ["1 kg chicken pieces or 700g lamb, cut into chunks",
     "3 large onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp fresh ginger, grated",
     "4 garlic cloves, minced",
     "1 green chilli (optional, for mild heat)",
     "1/2 cup water",
     "Salt to taste",
     "Injera to serve"],
    [("Cook onions", "Melt niter kibbeh in pot, add onions and cook 12 min until very soft and golden."),
     ("Add aromatics", "Add garlic, ginger, turmeric, and green chilli. Stir 3 min — do NOT add berbere."),
     ("Add meat", "Add meat pieces, turn to coat. Cook uncovered 8 min."),
     ("Simmer", "Add water, cover, simmer on low heat 35–40 min until meat is tender."),
     ("Finish", "Uncover and cook 5 min to thicken sauce. Season with salt. The colour should be golden-yellow, not red.")],
    sp="mild", prep=15, cook=50, sv=4,
    story="Alicha means 'mild' in Amharic. This is the gentle, turmeric-golden version of Ethiopian stew — perfect for those who cannot eat spicy food.")

RECIPES["Kik Alicha"] = lambda did: v(did, "Classic Kik Alicha",
    ["2 cups yellow split peas, soaked 1 hour and drained",
     "3 cups water",
     "2 large onions, finely chopped",
     "1 tsp turmeric",
     "3 tbsp vegetable oil",
     "3 garlic cloves, minced",
     "1 tsp fresh ginger, grated",
     "Salt to taste"],
    [("Boil split peas", "Place drained split peas in pot with 3 cups water. Bring to boil, skim foam, reduce heat, cook 20 min until just tender."),
     ("Sauté onions", "In separate pan, heat oil, cook onions 8 min. Add turmeric, garlic, ginger — cook 3 min."),
     ("Combine", "Add cooked peas (with their liquid) into the onion pot. Stir to combine."),
     ("Simmer", "Cook together 10–12 min, stirring occasionally, until thick and creamy. Slightly mash some peas with spoon."),
     ("Season", "Adjust salt. Serve on injera — the colour should be bright yellow-gold.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=35, sv=4)

RECIPES["Atkilt Wat"] = lambda did: v(did, "Classic Atkilt Wat",
    ["1/2 medium head green cabbage, cut into strips",
     "3 medium carrots, sliced into rounds",
     "3 medium potatoes, peeled and cubed",
     "2 onions, sliced into half-moons",
     "1 tsp turmeric",
     "1 tsp cumin",
     "3 tbsp vegetable oil",
     "3 garlic cloves, minced",
     "1 jalapeño, sliced (optional)",
     "Salt and black pepper to taste"],
    [("Sauté onions", "Heat oil in wide pot. Add onions and cook over medium heat 8 min until soft."),
     ("Add spices", "Add turmeric, cumin, and garlic. Stir 2 min."),
     ("Add potatoes and carrots", "Add potatoes and carrots, stir to coat in spices. Cook 8 min."),
     ("Add cabbage", "Add cabbage and jalapeño. Toss everything together."),
     ("Steam-cook", "Add 3 tbsp water, cover tightly, reduce heat to low. Cook 15 min until all vegetables are tender."),
     ("Finish", "Season with salt and pepper. Serve mounded on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=15, cook=30, sv=4,
    story="Atkilt Wat is one of the most common fasting dishes eaten during Orthodox fasting periods. Simple, satisfying, and nourishing.")

RECIPES["Bozena Shiro"] = lambda did: v(did, "Classic Bozena Shiro",
    ["1 cup shiro powder",
     "200g beef or lamb, cut into small 2cm chunks",
     "2 large onions, finely chopped",
     "3 tbsp oil",
     "1 tbsp berbere",
     "1 tbsp garlic paste",
     "3 cups water",
     "Salt to taste"],
    [("Brown meat", "Heat 1 tbsp oil in pot over high heat. Sear meat chunks until browned on all sides, about 5 min. Remove and set aside."),
     ("Make shiro base", "In same pot, cook onions in remaining oil 10 min. Add berbere and garlic, cook 3 min."),
     ("Add water", "Pour in water, bring to gentle boil."),
     ("Whisk shiro", "Slowly whisk in shiro powder. Stir constantly 2 min to prevent lumps."),
     ("Add meat back", "Return browned meat to pot. Simmer together on low heat 15 min, stirring often, until thick."),
     ("Serve", "Adjust salt. Serve hot — the meat chunks should be visible throughout the shiro.")],
    sp="medium", prep=15, cook=35, sv=4,
    story="Bozena Shiro elevates the everyday shiro by adding meat — making it a special occasion dish.")

RECIPES["Yesiga Alicha"] = lambda did: v(did, "Classic Yesiga Alicha",
    ["700g beef (chuck or shoulder), cut into chunks",
     "3 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp garlic paste",
     "1 tbsp ginger, grated",
     "1 cup water",
     "Salt to taste"],
    [("Cook onions", "Melt niter kibbeh, cook onions 12 min until golden."),
     ("Add spices", "Add turmeric, garlic, ginger. Cook 3 min. Do not add berbere."),
     ("Add beef", "Add beef, turn to coat. Cook 8 min uncovered."),
     ("Braise", "Add water, cover, simmer 45 min until very tender."),
     ("Finish", "Uncover, cook 5 min to reduce sauce. Season. Sauce should be golden.")],
    sp="mild", prep=15, cook=60, sv=4)

RECIPES["Doro Alicha"] = lambda did: v(did, "Classic Doro Alicha",
    ["1 kg chicken pieces",
     "3 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp garlic paste",
     "1 tsp ginger paste",
     "1/2 cup water",
     "Salt to taste"],
    [("Cook onions", "Cook onions in niter kibbeh 12 min until golden."),
     ("Add turmeric and aromatics", "Add turmeric, garlic, ginger — cook 3 min."),
     ("Add chicken", "Add chicken, coat well, cook 8 min."),
     ("Simmer", "Add water, cover, simmer 30 min until cooked through."),
     ("Finish", "Uncover and reduce sauce 5 min. Season with salt.")],
    sp="mild", prep=15, cook=45, sv=4)


# ── Raw & Tartare ────────────────────────────────────────────────────────────

RECIPES["Kitfo"] = lambda did: v(did, "Classic Kitfo",
    ["400g very fresh, very lean beef (tenderloin or top round), finely hand-minced — NOT ground",
     "2 tbsp niter kibbeh, gently warmed",
     "1 tsp mitmita spice blend",
     "1/4 tsp cardamom",
     "Salt to taste",
     "Ayib (Ethiopian cottage cheese) to serve",
     "Gomen (collard greens) to serve",
     "Injera or kita flatbread to serve"],
    [("Choose the beef", "Use only the freshest, highest quality lean beef. Ask your butcher to mince it finely by hand. The fat content must be very low."),
     ("Warm the niter kibbeh", "Warm niter kibbeh gently over low heat until just melted — do NOT make it hot. Stir in mitmita and cardamom."),
     ("Mix", "Place minced beef in a bowl. Pour the warm spiced butter over it. Mix quickly and thoroughly with your hands until every strand of meat is coated."),
     ("Taste and season", "Taste a small piece and adjust mitmita and salt to your preference."),
     ("Serve immediately", "Plate at once with ayib on the side and gomen. Serve with injera or kita. For 'leb leb' (medium), flash-cook in a hot pan for just 2 min — the inside stays pink."),
     ("Leftovers", "Kitfo must be eaten immediately. Never store raw kitfo.")],
    tags=["gluten_free"],
    sp="hot", prep=20, cook=0, sv=2,
    story="Kitfo is the crown jewel of Gurage cuisine, traditionally served at weddings and celebrations. The Gurage people of central Ethiopia consider it a symbol of hospitality and abundance. True kitfo is always served with homemade ayib and gomen.",
    notes="Leb leb means slightly cooked. Ye'lebs means fully cooked. Most Ethiopians prefer leb leb or raw.")

RECIPES["Gored Gored"] = lambda did: v(did, "Classic Gored Gored",
    ["400g very fresh lean beef (tenderloin), cut into 2cm cubes",
     "2 tbsp niter kibbeh, melted",
     "1 tsp mitmita",
     "1 tbsp awaze (Ethiopian chilli paste)",
     "1/2 tsp cardamom",
     "Salt to taste",
     "Injera to serve"],
    [("Cut the beef", "Cut tenderloin into neat 2cm cubes. The pieces should be uniform."),
     ("Season", "Mix melted niter kibbeh, mitmita, cardamom, and a pinch of salt in a bowl."),
     ("Toss", "Add beef cubes to the spiced butter. Toss to coat every surface. For leb leb, quickly sear in a very hot dry pan for 60–90 seconds — the outside colours but the inside stays rare."),
     ("Add awaze", "Transfer to plate, drizzle with awaze to taste."),
     ("Serve", "Serve immediately on injera.")],
    tags=["gluten_free"],
    sp="hot", prep=15, cook=0, sv=2,
    story="Gored Gored is the cubed raw beef version of Kitfo, popular in Addis Ababa restaurants. The name means 'cut cut' in Amharic.")

RECIPES["Dulet"] = lambda did: v(did, "Classic Dulet",
    ["200g cleaned tripe, finely minced",
     "200g beef liver, finely minced",
     "200g very lean beef, finely minced",
     "2 large red onions, finely chopped",
     "2 tbsp niter kibbeh",
     "1 tbsp mitmita",
     "1 jalapeño, finely minced",
     "Salt to taste",
     "Injera to serve"],
    [("Prep meats", "Mince each meat separately very finely. Keep them separated."),
     ("Sauté onions", "Heat niter kibbeh in pan, cook onions over medium heat 8 min until golden."),
     ("Add tripe", "Add minced tripe first — it takes longest. Cook 5 min, stirring."),
     ("Add beef", "Add minced beef. Stir and cook 3 min."),
     ("Add liver", "Add minced liver last — it cooks fastest. Stir 2 min. Liver should still be slightly pink inside."),
     ("Season", "Add mitmita, jalapeño, and salt. Toss everything together over high heat for 1 min."),
     ("Serve", "Serve immediately on injera. Dulet must be eaten hot.")],
    sp="hot", prep=20, cook=20, sv=3,
    story="Dulet is a delicacy made from the three key organ meats — tripe, liver, and lean beef. It is particularly popular during Timkat (Ethiopian Epiphany) and after fasting periods end.")

RECIPES["Tire Siga"] = lambda did: v(did, "Classic Tire Siga",
    ["500g the freshest possible lean beef, cut into thin strips",
     "Mitmita to serve",
     "Awaze to serve",
     "Niter kibbeh to serve",
     "Salt to serve",
     "Injera to serve"],
    [("Source the beef", "Tire Siga is only prepared with beef that has been slaughtered the same day. Freshness is everything — this dish cannot be made with refrigerated meat."),
     ("Slice", "Slice the beef very thinly against the grain into strips, or cut into small chunks."),
     ("Serve", "Arrange on a platter with small bowls of mitmita, awaze, and niter kibbeh on the side. Each person seasons their own piece at the table."),
     ("Eat", "Tear injera and wrap around a piece of beef with your choice of seasoning.")],
    tags=["gluten_free"],
    sp="hot", prep=10, cook=0, sv=4,
    notes="Tire Siga is only safe to eat with beef slaughtered the same day from a trusted source. It is never eaten the day after.",
    story="Tire Siga — 'fresh raw beef' — is a dish of pure trust between the host and guest. Serving it means you are offering only the very best.")

RECIPES["Kurt"] = lambda did: v(did, "Classic Kurt",
    ["500g very fresh lean beef",
     "Mitmita to taste",
     "Awaze to taste",
     "Salt to taste",
     "Injera to serve"],
    [("Cut", "Cut beef into bite-size chunks."),
     ("Season at table", "Place beef on injera. Each person seasons their portion with mitmita, awaze, and salt to their preference."),
     ("Cook if desired", "For cooked kurt, quickly sear chunks in hot dry pan 1–2 min per side — slightly charred outside, pink inside.")],
    tags=["gluten_free"],
    sp="medium", prep=10, cook=0, sv=4)

# ── Tibs / Sautéed ───────────────────────────────────────────────────────────

RECIPES["Tibs"] = lambda did: v(did, "Classic Tibs",
    ["500g beef sirloin or lamb shoulder, cut into 3cm cubes",
     "2 medium red onions, sliced into half-rings",
     "2 jalapeños (Ye'abesha pepper), sliced lengthways",
     "2 medium tomatoes, diced",
     "2 tbsp niter kibbeh",
     "1 sprig fresh rosemary",
     "1/2 tsp black pepper",
     "Salt to taste",
     "Injera or bread to serve"],
    [("Heat the pan", "Heat a heavy cast-iron pan or wok over very high heat until almost smoking. Add niter kibbeh."),
     ("Sear the meat", "Add beef or lamb in a single layer. Do NOT stir for 3–4 minutes — let a crust form. Then toss quickly."),
     ("Add aromatics", "Push meat to the side. Add onions, jalapeños, and rosemary sprig. Toss everything together."),
     ("Add tomatoes", "Add diced tomatoes and black pepper. Cook 4–5 min, stirring often."),
     ("Finish", "Everything should be slightly charred at the edges. Season with salt. Remove rosemary sprig. Serve immediately — tibs must be eaten hot.")],
    sp="medium", prep=15, cook=20, sv=3,
    story="Tibs is one of the most beloved everyday dishes in Ethiopia. It is cooked fast over high heat and served sizzling in a clay pot called a moseb.",
    notes="The secret to great tibs is extremely high heat and not overcrowding the pan. If you add too much meat at once it will steam instead of sear.")

RECIPES["Zilzil Tibs"] = lambda did: v(did, "Classic Zilzil Tibs",
    ["500g beef sirloin, sliced into long thin strips (5cm x 1cm)",
     "2 onions, sliced",
     "2 tbsp awaze (Ethiopian chilli paste)",
     "2 tbsp niter kibbeh",
     "1 sprig rosemary",
     "2 garlic cloves, minced",
     "1/2 tsp black pepper",
     "Salt to taste"],
    [("Marinate", "Toss beef strips with awaze, garlic, and a pinch of salt. Marinate 20 min."),
     ("Sear strips", "Heat niter kibbeh in hot pan over very high heat. Add beef strips in batches — sear 2 min per side until caramelised."),
     ("Add onions", "Add onions and rosemary. Toss and cook 4 min."),
     ("Finish", "Add black pepper. Adjust salt. Serve on injera, garnished with rosemary.")],
    sp="hot", prep=25, cook=15, sv=3,
    notes="Zilzil means 'strips' — the slicing is key. Cut strips across the grain for tenderness.")

RECIPES["Derek Tibs"] = lambda did: v(did, "Classic Derek Tibs",
    ["500g beef chuck or lamb, cut into 2cm cubes",
     "2 onions, sliced",
     "2 tbsp niter kibbeh",
     "2 jalapeños, sliced",
     "1/2 tsp berbere",
     "1 sprig rosemary",
     "Salt to taste"],
    [("Dry fry", "Heat heavy pan over high heat with NO fat first. Add meat cubes directly. Cook 5 min without stirring until very well browned and almost dry."),
     ("Add fat", "Add niter kibbeh. Toss to coat."),
     ("Add aromatics", "Add onions, jalapeños, rosemary, berbere. Cook 8 min tossing constantly."),
     ("Finish", "Meat should be crispy at edges, slightly dry. Season with salt. Serve immediately.")],
    sp="medium", prep=10, cook=20, sv=3,
    notes="Derek means 'dry' — this tibs is intentionally less saucy. The meat gets slightly crispy edges.")

RECIPES["Gomen Besiga"] = lambda did: v(did, "Classic Gomen Besiga",
    ["300g beef, cut into small 2cm pieces",
     "1 large bunch collard greens, stems removed, thinly sliced",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tbsp ginger, grated",
     "2 tbsp niter kibbeh",
     "1 jalapeño, sliced",
     "Salt to taste"],
    [("Cook beef", "Sear beef pieces in niter kibbeh over high heat until browned, about 5 min. Remove and set aside."),
     ("Sauté aromatics", "In same pan cook onions 8 min, add garlic, ginger, jalapeño — cook 3 min."),
     ("Add greens", "Add collard greens. Toss vigorously 3 min."),
     ("Combine", "Return beef to pan. Add 3 tbsp water, cover, cook 10 min until greens are tender."),
     ("Season", "Adjust salt. Serve with injera.")],
    sp="mild", prep=15, cook=25, sv=4)

RECIPES["Ye'abesha Gomen"] = lambda did: v(did, "Classic Ye'abesha Gomen",
    ["1 large bunch collard greens or Ethiopian kale, stems removed, finely sliced",
     "2 onions, thinly sliced",
     "3 garlic cloves, minced",
     "1 tsp ginger, grated",
     "2 tbsp niter kibbeh",
     "1/2 tsp turmeric",
     "Salt to taste"],
    [("Blanch greens", "Bring a large pot of salted water to boil. Add collard greens and boil 5 min. Drain well, squeeze out excess water."),
     ("Sauté", "Heat niter kibbeh in pan. Cook onions 8 min. Add garlic, ginger, turmeric — cook 3 min."),
     ("Add greens", "Add blanched greens. Toss well. Cook 10–12 min until fully tender."),
     ("Season", "Adjust salt. Serve alongside other dishes on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free"],
    sp="mild", prep=15, cook=25, sv=4)

RECIPES["Fosolia"] = lambda did: v(did, "Classic Fosolia",
    ["300g fresh green beans, trimmed and cut in half",
     "2 medium carrots, cut into thin matchsticks",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tsp ginger, grated",
     "2 tbsp vegetable oil",
     "1/2 tsp turmeric",
     "Salt and black pepper to taste"],
    [("Blanch beans", "Blanch green beans in boiling salted water for 3 min. Drain and set aside."),
     ("Sauté", "Heat oil, cook onions 6 min. Add garlic, ginger, turmeric — cook 2 min."),
     ("Add vegetables", "Add carrots and blanched beans. Toss to coat in spices."),
     ("Cook", "Stir-fry over medium-high heat for 8–10 min until carrots are tender but still have bite."),
     ("Season", "Add salt and pepper. Serve as a side dish on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=20, sv=4)

RECIPES["Gomen"] = lambda did: v(did, "Classic Gomen",
    ["1 large bunch collard greens or kale, stems removed, roughly chopped",
     "2 large onions, sliced",
     "4 garlic cloves, minced",
     "1 tbsp fresh ginger, grated",
     "3 tbsp vegetable oil",
     "1 fresh jalapeño, sliced",
     "Salt to taste"],
    [("Blanch greens", "Boil greens in salted water 5 min, drain and squeeze dry."),
     ("Sauté base", "Heat oil in wide pan. Cook onions 10 min until golden."),
     ("Add aromatics", "Add garlic, ginger, jalapeño. Cook 3 min."),
     ("Add greens", "Add drained greens, toss to combine everything."),
     ("Cook down", "Cook over medium heat 10–12 min, tossing occasionally, until greens are fully tender and flavourful."),
     ("Season", "Adjust salt. Serve on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=15, cook=25, sv=4)


# ── Injera & Firfir ──────────────────────────────────────────────────────────

RECIPES["Injera"] = lambda did: v(did, "Classic Teff Injera",
    ["3 cups teff flour (pure teff, not mixed)",
     "3 cups water (filtered or room temperature)",
     "1/2 tsp salt",
     "Extra water for adjusting batter consistency"],
    [("Mix batter", "Combine teff flour and water in a large bowl. Whisk until completely smooth with no lumps. The batter should be pourable — like thin pancake batter."),
     ("Ferment", "Cover bowl loosely with a cloth (not plastic — it needs to breathe). Leave at room temperature for 2–3 days. In warm weather (25°C+) it may be ready in 1.5 days. You will see bubbles forming and it will smell pleasantly sour."),
     ("Check batter", "When ready, the batter will be bubbly, slightly thickened, and sour-smelling. Stir gently. Adjust consistency with a little water if too thick — it should pour easily."),
     ("Add salt", "Stir in salt just before cooking."),
     ("Heat the pan", "Heat a large non-stick pan or mitad (injera griddle) over medium-high heat until very hot. Do not use oil."),
     ("Pour and cook", "Pour batter in a circular motion from the outside in, filling the pan in one smooth motion. Cover immediately with a lid."),
     ("Watch for eyes", "Cook for exactly 2 minutes until all the 'eyes' (holes) on the surface have dried and the edges begin to lift. Do NOT flip."),
     ("Remove", "Slide injera onto a clean cloth or rack. Do not stack until completely cool.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=5, cook=30, sv=6,
    story="Injera is not just a bread — it is the plate, the utensil, and the food all in one. Teff, the ancient Ethiopian grain, gives it a distinctive sour flavour and high nutritional value including iron and calcium.",
    notes="Real injera needs 2–3 days fermentation. Shortcuts produce flat tasteless results. The fermented starter from a previous batch (ersho) will speed up future batches.")

RECIPES["Firfir"] = lambda did: v(did, "Classic Firfir",
    ["2 large onions, finely chopped",
     "1/4 cup vegetable oil",
     "2 tbsp berbere spice blend",
     "1 tbsp garlic paste",
     "2 medium tomatoes, diced",
     "1 cup water",
     "Salt to taste",
     "2 pieces day-old injera, torn into 5cm pieces"],
    [("Cook onions", "Heat oil in wide pan. Cook onions over medium heat 12–15 min until deep golden. Don't rush this."),
     ("Add berbere", "Add berbere and garlic paste. Stir constantly for 5 min until very fragrant and dark."),
     ("Add tomatoes", "Add diced tomatoes. Cook 5 min until broken down."),
     ("Add water", "Pour in 1 cup water, stir, simmer 5 min to create a thick sauce."),
     ("Add injera", "Add torn injera pieces. Fold gently to coat every piece. Cook 3–4 min — injera will absorb the sauce and soften."),
     ("Season", "Adjust salt. Serve hot. Firfir is best eaten immediately while warm.")],
    tags=["vegan", "fasting_friendly"],
    sp="hot", prep=10, cook=30, sv=2,
    story="Firfir is Ethiopia's answer to using leftover injera. Day-old injera works best as it holds its shape while absorbing the sauce.",
    notes="Use day-old injera — fresh injera will dissolve too quickly.")

RECIPES["Quanta Firfir"] = lambda did: v(did, "Classic Quanta Firfir",
    ["200g quanta (Ethiopian dried beef strips), soaked in water 30 min",
     "2 large onions, finely chopped",
     "2 tbsp berbere",
     "2 tbsp niter kibbeh",
     "1 tbsp garlic paste",
     "Salt to taste",
     "2 pieces injera, torn into pieces"],
    [("Soak quanta", "Soak dried beef strips in cold water for 30 min until rehydrated and slightly softened."),
     ("Cook onions", "Heat niter kibbeh, cook onions 12 min until golden."),
     ("Add berbere", "Add berbere and garlic. Cook 5 min."),
     ("Add quanta", "Drain quanta and add to pot. Stir to coat in the sauce. Cook 10 min — the beef will absorb flavour and become tender."),
     ("Add injera", "Fold in torn injera. Cook 3 min, coating all pieces."),
     ("Season", "Adjust salt. Serve immediately.")],
    sp="hot", prep=35, cook=30, sv=3,
    story="Quanta is beef that has been dried in the sun with salt and spices — Ethiopia's version of jerky. Quanta Firfir is a rich, meaty firfir popular in Gondar and Amhara regions.")

RECIPES["Enqulal Firfir"] = lambda did: v(did, "Classic Enqulal Firfir",
    ["4 eggs",
     "2 pieces injera, torn into pieces",
     "2 medium tomatoes, diced",
     "1 onion, finely diced",
     "2 jalapeños, sliced",
     "2 tbsp vegetable oil",
     "Salt to taste"],
    [("Sauté base", "Heat oil in pan. Cook onion 5 min, add tomatoes and jalapeños, cook 5 min."),
     ("Scramble eggs", "Beat eggs with a pinch of salt. Pour into pan. Stir gently to scramble, keeping large curds."),
     ("Add injera", "When eggs are just set but still moist, fold in torn injera pieces. Stir to combine."),
     ("Serve", "Serve immediately in the pan or on a plate. Eat for breakfast.")],
    sp="medium", prep=5, cook=15, sv=2,
    notes="This is a beloved quick Ethiopian breakfast — ready in 15 minutes.")

RECIPES["Kategna"] = lambda did: v(did, "Classic Kategna",
    ["2 pieces injera (fresh or day-old)",
     "2 tbsp niter kibbeh, softened",
     "1 tbsp berbere spice blend",
     "Optional: pinch of salt"],
    [("Mix spread", "Mix softened niter kibbeh with berbere to make a spiced spread."),
     ("Spread", "Spread generously over one side of each injera."),
     ("Toast", "Place injera spread-side up on a hot dry griddle or directly over a low gas flame. Toast until the edges crisp up and the bottom chars slightly, about 3–4 min."),
     ("Serve", "Cut or fold and serve as a snack or starter.")],
    sp="medium", prep=3, cook=5, sv=2,
    story="Kategna is Ethiopia's ultimate street snack — toasted injera with spiced butter. Sold at every tej bet (honey wine house) as a bar snack.")

# ── Breakfast ────────────────────────────────────────────────────────────────

RECIPES["Chechebsa"] = lambda did: v(did, "Classic Chechebsa",
    ["2 kita flatbreads (thin unleavened wheat flatbreads)",
     "3 tbsp niter kibbeh",
     "1 tbsp berbere spice blend",
     "1 tbsp honey (to serve)",
     "Optional: pinch of salt"],
    [("Make kita", "Mix 2 cups flour, pinch of salt, and enough water to make a stiff dough. Rest 10 min. Roll thin (3–4mm). Cook in dry pan 2–3 min per side until cooked through."),
     ("Shred", "While still warm, tear kita into rough 3–4cm pieces."),
     ("Heat niter kibbeh", "Warm niter kibbeh in a wide pan over medium heat. Add berbere, stir 30 seconds."),
     ("Toss", "Add kita pieces to the pan. Toss vigorously to coat every piece in the spiced butter. Cook 3 min until heated through."),
     ("Serve", "Transfer to plate. Drizzle honey over the top. Serve immediately for breakfast.")],
    sp="medium", prep=15, cook=15, sv=2,
    story="Chechebsa is a traditional Oromo breakfast from central Ethiopia. The combination of spicy berbere and sweet honey is a uniquely Ethiopian flavour balance.")

RECIPES["Genfo"] = lambda did: v(did, "Classic Genfo",
    ["1 cup teff flour (or barley flour for a milder taste)",
     "3 cups water",
     "1/2 tsp salt",
     "2 tbsp niter kibbeh",
     "1 tsp berbere (or mitmita for extra heat)",
     "Optional: 1 tsp honey"],
    [("Boil water", "Bring salted water to a rolling boil in a heavy-bottomed pot."),
     ("Add flour", "Reduce heat to medium. Using a wooden spoon, slowly pour in teff flour while stirring constantly and vigorously to prevent any lumps."),
     ("Cook porridge", "Keep stirring constantly for 15 minutes. The porridge will become extremely thick — almost stiff. This is correct. It should pull away from the sides of the pot."),
     ("Shape", "Wet a bowl with water. Place the genfo in the bowl. Using the back of a wet spoon, shape into a smooth dome and press a well into the centre."),
     ("Add toppings", "Fill the well with niter kibbeh and dust berbere over the butter. The butter will melt and run into the grooves."),
     ("Serve", "Eat by scooping from the edges toward the centre, getting some of each flavour in each bite.")],
    tags=["gluten_free"],
    sp="medium", prep=5, cook=20, sv=2,
    story="Genfo is the first solid food given to Ethiopian babies, and also the food brought to new mothers after birth. It is deeply nourishing and warming.",
    notes="Genfo should be very thick — almost like stiff polenta. If it pours, it is not cooked enough.")

RECIPES["Ful Medames"] = lambda did: v(did, "Classic Ful Medames",
    ["2 cups dried fava beans (ful), soaked overnight and cooked until tender, OR 2 cans cooked fava beans",
     "Juice of 1 large lemon",
     "2 garlic cloves, very finely minced",
     "1 fresh jalapeño, finely diced",
     "3 tbsp good olive oil",
     "Salt to taste",
     "Optional toppings: diced tomato, diced onion, boiled egg, fresh herbs",
     "Injera or bread to serve"],
    [("Cook beans if dried", "Soak dried beans overnight. Drain, cover with fresh water, boil 45–60 min until completely tender. Drain, reserving some cooking liquid."),
     ("Mash", "Place warm beans in a bowl. Roughly mash with a fork — you want a mixture of mashed and whole beans."),
     ("Season", "Add lemon juice, garlic, jalapeño, olive oil, and salt. Mix well."),
     ("Adjust consistency", "If too thick, add a splash of the cooking liquid or water."),
     ("Add toppings", "Top with diced tomato, raw onion, and a drizzle of extra olive oil."),
     ("Serve", "Eat warm with injera, kita, or bread. Ful is best in the morning.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=15, sv=2,
    story="Ful Medames came to Ethiopia through trade with Egypt and Sudan, but has become completely Ethiopian — served in every tej bet and café as a breakfast staple.")

RECIPES["Enqulal Tibs"] = lambda did: v(did, "Classic Enqulal Tibs",
    ["4 large eggs",
     "2 medium tomatoes, diced",
     "1 onion, finely diced",
     "2 jalapeños or long green peppers, sliced",
     "2 tbsp niter kibbeh or butter",
     "Salt and black pepper to taste",
     "Injera to serve"],
    [("Heat butter", "Melt niter kibbeh in pan over medium heat."),
     ("Sauté vegetables", "Add onion and jalapeños. Cook 5 min until soft. Add tomatoes, cook 4 more min."),
     ("Add eggs", "Crack eggs directly into pan over vegetables. Season with salt and pepper."),
     ("Scramble", "Stir gently, keeping large soft curds. Remove from heat when just set — slightly runny is preferred."),
     ("Serve", "Serve immediately on injera.")],
    sp="medium", prep=5, cook=10, sv=2)

RECIPES["Kinche"] = lambda did: v(did, "Classic Kinche",
    ["1 cup cracked wheat (or cracked barley)",
     "2.5 cups water or milk",
     "1/2 tsp salt",
     "2 tbsp niter kibbeh",
     "Optional: honey or yogurt to serve"],
    [("Rinse", "Rinse cracked wheat briefly under cold water."),
     ("Cook", "Bring water/milk to boil in pot. Add cracked wheat and salt. Stir, reduce to low heat."),
     ("Simmer", "Cook covered 20–25 min until all liquid is absorbed and wheat is tender. Stir occasionally."),
     ("Finish", "Stir in niter kibbeh. Adjust salt."),
     ("Serve", "Serve warm in bowls with honey or yogurt alongside.")],
    tags=["vegetarian"],
    sp="mild", prep=5, cook=25, sv=2,
    story="Kinche is Ethiopia's comforting morning porridge, eaten across all regions. Simple to make and deeply satisfying.")

RECIPES["Teff Porridge"] = lambda did: v(did, "Classic Teff Porridge",
    ["1 cup whole teff grain (not flour)",
     "3 cups water or milk",
     "1/2 tsp salt",
     "1 tbsp honey",
     "Optional: cinnamon, cardamom"],
    [("Rinse teff", "Rinse teff in fine sieve under cold water."),
     ("Cook", "Bring liquid to boil. Add teff and salt. Stir, reduce to low heat, cover."),
     ("Simmer", "Cook 20 min until soft and porridge-like. Stir often."),
     ("Sweeten", "Stir in honey and any spices."),
     ("Serve", "Serve warm as breakfast porridge.")],
    tags=["gluten_free", "dairy_free", "vegan"],
    sp="mild", prep=5, cook=20, sv=2)


# ── Vegetarian / Fasting ─────────────────────────────────────────────────────

RECIPES["Beyaynetu"] = lambda did: v(did, "Classic Beyaynetu",
    ["Misir Wat (red lentil stew)",
     "Shiro Wat (chickpea stew)",
     "Gomen (collard greens)",
     "Atkilt Wat (cabbage and potato stew)",
     "Fosolia (green beans and carrots)",
     "Timatim Salad (tomato salad)",
     "Kik Alicha (yellow split peas)",
     "Large fresh injera to serve"],
    [("Prepare each dish", "Cook each component separately according to its own recipe. Plan to have everything ready at the same time."),
     ("Lay the injera", "Place one or two large injera on a wide round tray or mesob basket, overlapping to cover the surface completely."),
     ("Arrange", "Spoon each dish in a separate mound around the injera, alternating colours and textures. Leave space between each mound."),
     ("Serve", "Bring to the table. Guests tear pieces of injera and scoop up the different dishes. Everyone eats from the same tray — this communal eating is called 'gursha'.")],
    tags=["vegan", "fasting_friendly"],
    sp="medium", prep=30, cook=90, sv=4,
    story="Beyaynetu means 'of all kinds' in Amharic. This platter is the centrepiece of Ethiopian fasting meals, displaying the extraordinary variety of plant-based Ethiopian cuisine. During fasting periods, Ethiopian Orthodox Christians eat no meat or dairy — and beyaynetu shows that fasting food can be a feast.")

RECIPES["Timatim Salad"] = lambda did: v(did, "Classic Timatim Salad",
    ["4 ripe medium tomatoes, finely diced",
     "1 small red onion, very finely diced",
     "2 jalapeños or long green chillies, finely sliced",
     "Juice of 1 lemon",
     "2 tbsp good olive oil or vegetable oil",
     "Small handful fresh coriander or parsley, chopped (optional)",
     "Salt to taste"],
    [("Dice", "Dice tomatoes into 1cm pieces. Dice onion very small so it blends in rather than overpowers."),
     ("Combine", "Mix tomatoes, onion, and jalapeños in a bowl."),
     ("Dress", "Add lemon juice, oil, and salt. Toss gently."),
     ("Rest", "Let sit 10 minutes for flavours to develop."),
     ("Serve", "Taste and adjust lemon and salt. Scatter herbs if using. Serve alongside stews on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=0, sv=4,
    notes="The key is finely dicing the onion — large pieces are harsh. Small dice melts into the salad.")

RECIPES["Buticha"] = lambda did: v(did, "Classic Buticha",
    ["2 cups cooked chickpeas (canned is fine, drained and rinsed)",
     "2 tbsp good olive oil, plus extra to serve",
     "Juice of 1 large lemon",
     "2 garlic cloves, minced",
     "1 jalapeño, finely minced",
     "1/4 tsp turmeric",
     "Salt to taste",
     "Injera to serve"],
    [("Blend", "Place chickpeas, olive oil, lemon juice, garlic, jalapeño, and turmeric in a food processor or blender. Blend until very smooth."),
     ("Season", "Add salt and blend again. Taste — it should be bright, garlicky, and slightly spicy."),
     ("Adjust", "Add more lemon for brightness or more oil for richness."),
     ("Serve", "Spread on a plate, drizzle with olive oil, and serve chilled with injera for scooping.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=0, sv=4,
    story="Buticha is Ethiopia's version of hummus — but made with whole spices and jalapeño rather than tahini. It is a staple fasting dish across all regions.")

RECIPES["Tegabino"] = lambda did: v(did, "Classic Tegabino",
    ["1 cup roasted chickpea flour (shiro or besan)",
     "2 cups water",
     "2 tbsp niter kibbeh",
     "Salt to taste",
     "Berbere or mitmita to serve"],
    [("Toast the flour", "Heat a dry pan over medium heat. Add chickpea flour. Toast 3–4 minutes, stirring constantly, until fragrant and slightly darker. Do not burn."),
     ("Mix with water", "Gradually add water to the flour, whisking constantly to prevent lumps."),
     ("Cook", "Cook over medium heat, stirring constantly for 10 minutes until the porridge is thick, smooth, and pulls away from pan sides."),
     ("Add niter kibbeh", "Stir in niter kibbeh. Season with salt."),
     ("Serve", "Serve in a small clay pot or bowl. Dust with berbere on top. Eaten with a small spoon or injera.")],
    sp="medium", prep=5, cook=15, sv=2,
    story="Tegabino is the ultimate Ethiopian street food snack — sold by vendors outside churches and markets, especially during fasting periods.")

RECIPES["Fassolia"] = lambda did: v(did, "Classic Fassolia",
    ["2 cups dried white kidney beans or cannellini beans, soaked overnight and cooked until tender (or 2 cans, drained)",
     "2 medium tomatoes, diced",
     "2 onions, finely chopped",
     "3 garlic cloves, minced",
     "2 tbsp vegetable oil",
     "1 tsp turmeric",
     "1 jalapeño, sliced",
     "Salt to taste"],
    [("Cook onions", "Heat oil, cook onions 8 min until golden."),
     ("Add aromatics", "Add garlic, turmeric, jalapeño. Cook 3 min."),
     ("Add tomatoes", "Add diced tomatoes. Cook 5 min until broken down."),
     ("Add beans", "Add cooked beans. Stir to coat in sauce. Add 1/4 cup water."),
     ("Simmer", "Cook 10 min until sauce is thick and beans are well flavoured."),
     ("Season", "Adjust salt. Serve on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=25, sv=4)

RECIPES["Yetsom Beyaynetu"] = lambda did: v(did, "Strict Fasting Platter",
    ["Misir Wat (no niter kibbeh — use oil)",
     "Kik Alicha (cooked with oil only)",
     "Gomen (cooked with oil only)",
     "Tikel Gomen (shredded cabbage)",
     "Fosolia (green beans)",
     "Timatim Salad",
     "Injera (made with only teff and water)"],
    [("Prepare all dishes", "Cook each dish using only vegetable oil — no niter kibbeh, no butter, no honey, no eggs, no animal products of any kind."),
     ("Verify fasting compliance", "Each dish must be free from all animal products including honey and dairy."),
     ("Arrange", "Lay injera on a round tray. Spoon each dish in separate mounds."),
     ("Serve", "Serve communally for breaking strict fasting days.")],
    tags=["vegan", "fasting_friendly", "dairy_free"],
    sp="medium", prep=30, cook=90, sv=4,
    story="During the strictest fasting days — such as Ye'Tsom periods and Wednesdays and Fridays — Ethiopian Orthodox Christians eat only completely vegan food. This platter honours that tradition.")

RECIPES["Dinich Alicha"] = lambda did: v(did, "Classic Dinich Alicha",
    ["4 medium potatoes, peeled and cut into 3cm cubes",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tsp turmeric",
     "1 tsp ginger, grated",
     "2 tbsp vegetable oil",
     "Salt to taste"],
    [("Cook onions", "Heat oil, cook onions 8 min."),
     ("Add spices", "Add garlic, ginger, turmeric. Cook 2 min."),
     ("Add potatoes", "Add potatoes, toss to coat."),
     ("Cook", "Add 1/4 cup water, cover, cook 15–18 min until potatoes are completely tender."),
     ("Finish", "Uncover, cook 2 min. Season with salt.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=25, sv=4)

RECIPES["Tikel Gomen"] = lambda did: v(did, "Classic Tikel Gomen",
    ["1/2 head green cabbage, thinly shredded",
     "2 carrots, grated or thinly sliced",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tsp turmeric",
     "1 tsp ginger",
     "2 tbsp vegetable oil",
     "1 jalapeño, sliced",
     "Salt to taste"],
    [("Cook onions", "Heat oil, cook onions 6 min."),
     ("Add spices", "Add garlic, ginger, turmeric, jalapeño. Cook 2 min."),
     ("Add carrots", "Add carrots, cook 3 min."),
     ("Add cabbage", "Add shredded cabbage, toss well with everything."),
     ("Cook down", "Cook 8–10 min tossing often until cabbage is wilted and tender but not mushy."),
     ("Season", "Adjust salt. Serve.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=20, sv=4)

RECIPES["Yemisir Kik"] = lambda did: v(did, "Classic Yemisir Kik",
    ["2 cups red split lentils, rinsed",
     "4 cups water",
     "2 onions, finely chopped",
     "1 tsp turmeric",
     "2 tbsp vegetable oil",
     "2 garlic cloves, minced",
     "Salt to taste"],
    [("Cook lentils", "Boil lentils in water 15 min. They should be soft but not mushy."),
     ("Sauté", "In separate pan, cook onions in oil 8 min. Add turmeric and garlic, cook 2 min."),
     ("Combine", "Add lentils with cooking liquid to onion pan. Stir and simmer 10 min."),
     ("Season", "Adjust salt. This should be milder and thinner than Misir Wat.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=5, cook=30, sv=4)


# ── Snacks & Street Food ─────────────────────────────────────────────────────

RECIPES["Sambusa"] = lambda did: v(did, "Lentil Sambusa",
    ["For the dough: 2 cups plain flour, 1/2 tsp salt, 3/4 cup warm water, 2 tbsp oil",
     "For the filling: 1 cup red or green lentils, cooked and drained",
     "1 onion, finely diced",
     "2 jalapeños, finely diced",
     "1 tsp cumin",
     "1 tsp coriander",
     "Salt to taste",
     "Oil for deep frying"],
    [("Make dough", "Mix flour, salt, oil, and warm water into a firm dough. Knead 5 min until smooth. Cover and rest 20 min."),
     ("Make filling", "Cook onion in 1 tbsp oil 5 min. Add jalapeños, cumin, coriander — cook 2 min. Add drained lentils and salt. Mash slightly. Cool completely."),
     ("Roll dough", "Divide dough into 12 balls. Roll each into a thin circle (15cm)."),
     ("Shape", "Cut circle in half. Fold each half into a cone, sealing the straight edge with a little water."),
     ("Fill and seal", "Fill cone with 1 tbsp filling. Pinch the open top firmly closed. Press edges to seal well — no gaps."),
     ("Fry", "Heat oil to 170°C. Fry sambusa in batches 3–4 min, turning once, until deep golden brown."),
     ("Drain", "Drain on paper towels. Serve hot.")],
    tags=["vegan", "fasting_friendly"],
    sp="medium", prep=40, cook=20, sv=12,
    story="Sambusa arrived in Ethiopia through Arab and Indian trade routes but has become entirely Ethiopian — the most popular street food snack during Ramadan and fasting periods.")

RECIPES["Andeguday"] = lambda did: v(did, "Classic Andeguday",
    ["2 cups plain flour",
     "1/2 tsp salt",
     "3/4 cup warm water",
     "For filling: 200g minced beef OR 1 cup lentils",
     "1 onion, finely diced",
     "1 tbsp berbere",
     "Oil for frying"],
    [("Make dough", "Mix flour, salt, water into a firm dough. Rest 15 min."),
     ("Cook filling", "Fry onion 5 min. Add berbere and beef/lentils. Cook 8 min. Season. Cool."),
     ("Shape", "Roll dough thin. Cut into squares (10cm). Place filling in centre."),
     ("Seal", "Fold into a pocket or half-moon. Press edges firmly."),
     ("Fry", "Fry in hot oil until golden, about 3 min per side.")],
    sp="medium", prep=30, cook=20, sv=8,
    story="Andeguday is the Tigrayan version of a filled fried pastry — a speciality of northern Ethiopia.")

RECIPES["Dabo Kolo"] = lambda did: v(did, "Classic Dabo Kolo",
    ["2 cups plain flour",
     "1 tsp berbere",
     "1/2 tsp salt",
     "1/2 tsp black pepper",
     "2 tbsp vegetable oil",
     "1/2 cup water (approximately)"],
    [("Mix dough", "Combine flour, berbere, salt, pepper, and oil. Add water gradually until a firm dough forms — stiffer than bread dough."),
     ("Rest", "Cover and rest 15 min."),
     ("Roll and cut", "Roll dough to 5mm thickness. Cut into 1cm x 3cm small rectangles or roll into small balls."),
     ("Bake or fry", "BAKE: Place on baking tray, bake 180°C for 20 min until crispy and dry. FRY: Deep fry at 160°C for 3–4 min until golden."),
     ("Cool", "Cool completely — they crisp up as they cool. Store in an airtight container.")],
    tags=["vegan"],
    sp="medium", prep=20, cook=20, sv=6,
    story="Dabo Kolo are Ethiopia's answer to crackers — crunchy spiced dough bites eaten as snacks, packed for travel, or served with drinks.")

RECIPES["Kolo"] = lambda did: v(did, "Classic Kolo",
    ["1 cup barley, roasted",
     "1/2 cup chickpeas, roasted",
     "1/4 cup sunflower seeds",
     "1/4 cup peanuts",
     "1/2 tsp salt",
     "Optional: pinch of berbere or mitmita"],
    [("Roast barley", "Toast barley in dry pan over medium heat 8–10 min, stirring constantly, until golden and popped. Transfer to bowl."),
     ("Roast chickpeas", "In same dry pan, roast chickpeas 6–8 min until crispy."),
     ("Combine", "Mix all ingredients together. Season with salt and spices."),
     ("Cool and serve", "Cool completely. Store in airtight container for up to 2 weeks.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=5, cook=20, sv=8,
    story="Kolo is Ethiopia's trail mix — carried by travellers, hikers, and farmers. It is the oldest Ethiopian snack food.")

RECIPES["Fetira"] = lambda did: v(did, "Classic Fetira with Honey",
    ["2 cups plain flour",
     "1/2 tsp salt",
     "3/4 cup warm water",
     "2 tbsp oil for frying",
     "Honey to serve",
     "Optional: 2 eggs for filled version"],
    [("Make dough", "Mix flour, salt, and water into a soft dough. Knead 3 min. Rest 10 min."),
     ("Roll thin", "Divide into 4 balls. Roll each into a very thin circle (2–3mm)."),
     ("Fry", "Heat oil in pan over medium-high heat. Fry each fetira 2 min per side until golden with some crispy bubbles."),
     ("Serve", "Drizzle generously with honey while still hot.")],
    sp="mild", prep=15, cook=15, sv=4,
    story="Fetira is a thin fried bread sold by street vendors, especially in Addis Ababa. Drizzled with honey, it is breakfast, dessert, and snack all in one.")


# ── Condiments ───────────────────────────────────────────────────────────────

RECIPES["Niter Kibbeh"] = lambda did: v(did, "Classic Niter Kibbeh",
    ["500g good quality unsalted butter",
     "1 medium onion, roughly chopped",
     "4 garlic cloves, crushed",
     "1 tbsp fresh ginger, grated",
     "1/2 tsp turmeric",
     "1/4 tsp cardamom",
     "1 cinnamon stick",
     "2 whole cloves",
     "1/4 tsp fenugreek seeds"],
    [("Melt butter slowly", "Place butter in a heavy saucepan over very low heat. Allow to melt completely without browning."),
     ("Add aromatics", "Add onion, garlic, ginger, and all spices. Do NOT let it boil — it should only gently simmer with small bubbles."),
     ("Infuse", "Simmer on lowest heat for 25–30 min. The milk solids will settle at the bottom and the butter will become clear and golden."),
     ("Watch carefully", "Do not let it boil hard or the butter will burn. The onions should gently cook but not colour."),
     ("Strain", "Pour through a fine mesh sieve lined with muslin cloth into a clean glass jar. Discard solids."),
     ("Cool and store", "Cool to room temperature. It solidifies when cool. Keeps 3 months at room temperature, 6 months refrigerated.")],
    tags=["gluten_free"],
    sp="mild", prep=5, cook=30, sv=16,
    story="Niter kibbeh is the soul of Ethiopian cooking. Almost every savoury Ethiopian dish uses it as a base. No other fat gives the same depth of flavour.",
    notes="The key is very low heat throughout. If you hear aggressive sizzling, the heat is too high.")

RECIPES["Ayib"] = lambda did: v(did, "Classic Ayib",
    ["2 litres full-fat whole milk",
     "3 tbsp fresh lemon juice or white vinegar",
     "1/2 tsp salt"],
    [("Heat milk", "Pour milk into pot and heat over medium heat, stirring occasionally, until it reaches just below boiling point (80–85°C). Small bubbles around the edges — do NOT boil."),
     ("Add acid", "Remove from heat. Add lemon juice. Stir gently once. Leave completely undisturbed for 10 minutes."),
     ("Check curds", "The milk should have separated into white curds and yellowish-green whey. If not, add 1 more tbsp lemon juice."),
     ("Drain", "Line a colander with a clean muslin cloth. Pour curds in. Gather the cloth and tie it. Hang over a bowl for 1–2 hours or press with a plate."),
     ("Season", "Remove from cloth. Season with salt. Crumble into pieces."),
     ("Serve", "Serve alongside kitfo, gomen, or on beyaynetu.")],
    tags=["gluten_free"],
    sp="mild", prep=5, cook=20, sv=6,
    story="Ayib is Ethiopia's fresh cottage cheese — always made same-day. It is the cooling counterpart to spicy kitfo, cutting through the heat with its mild creaminess.")

RECIPES["Berbere"] = lambda did: v(did, "Homemade Berbere Spice Blend",
    ["8 dried red chillies (mild-medium heat), stems removed",
     "1 tsp fenugreek seeds",
     "1 tsp coriander seeds",
     "1/2 tsp cumin seeds",
     "1/4 tsp black pepper",
     "1/4 tsp cardamom seeds",
     "1/4 tsp allspice berries",
     "1 small cinnamon stick",
     "4 whole cloves",
     "1/2 tsp ginger powder",
     "1/2 tsp onion powder",
     "Salt to taste"],
    [("Toast whole spices", "Toast coriander, cumin, fenugreek, cardamom, allspice, cinnamon, and cloves in dry pan over medium heat 2–3 min until fragrant. Do NOT burn."),
     ("Cool", "Transfer to plate and cool completely."),
     ("Grind", "Grind toasted spices with the dried chillies in a spice grinder until fine powder."),
     ("Mix", "Add ginger powder, onion powder, and salt. Mix thoroughly."),
     ("Store", "Store in airtight jar away from light. Keeps 3 months.")],
    tags=["vegan", "gluten_free", "dairy_free"],
    sp="hot", prep=10, cook=5, sv=20,
    story="Berbere is the heart of Ethiopian cuisine — every household has its own recipe, passed down through generations. Commercial berbere never matches homemade.",
    notes="The ratio of chillies determines the heat. Start with fewer and add more to taste.")

RECIPES["Mitmita"] = lambda did: v(did, "Homemade Mitmita",
    ["20 dried bird's eye chillies or African bird chillies",
     "1/2 tsp cardamom seeds",
     "1/4 tsp cloves",
     "1/4 tsp cinnamon",
     "Salt to taste"],
    [("Toast", "Lightly toast cardamom, cloves, and cinnamon in dry pan 1 min."),
     ("Grind", "Grind all ingredients including chillies into a fine orange-red powder."),
     ("Store", "Store in airtight jar. Very potent — use sparingly.")],
    tags=["vegan", "gluten_free"],
    sp="hot", prep=5, cook=5, sv=20,
    notes="Mitmita is much hotter than berbere. Use very small amounts.")

RECIPES["Awaze"] = lambda did: v(did, "Classic Awaze",
    ["3 tbsp berbere spice blend",
     "2 tbsp tej (Ethiopian honey wine) or dry white wine",
     "1 tbsp niter kibbeh, melted",
     "1 garlic clove, minced",
     "Salt to taste"],
    [("Combine", "Mix berbere, tej, melted niter kibbeh, and garlic in a bowl."),
     ("Stir", "Mix into a thick, smooth paste."),
     ("Season", "Add salt. Adjust tej for desired consistency."),
     ("Serve", "Use as a dipping sauce for tibs, raw beef, or grilled meats.")],
    tags=["gluten_free"],
    sp="hot", prep=5, cook=0, sv=6,
    story="Awaze is Ethiopia's signature condiment — a fiery, butter-rich chilli paste served with virtually every meat dish.")

# ── Breads ───────────────────────────────────────────────────────────────────

RECIPES["Kita"] = lambda did: v(did, "Classic Kita",
    ["2 cups plain flour (or teff flour for teff kita)",
     "1/2 tsp salt",
     "3/4 cup warm water"],
    [("Make dough", "Mix flour, salt, and enough water to form a firm dough. Knead 3 min."),
     ("Rest", "Cover and rest 10 min."),
     ("Roll", "Roll dough into a thin round (3–4mm) the size of your pan."),
     ("Cook", "Place in dry pan over medium heat. Cook 3 min per side until cooked through with some charred spots."),
     ("Serve", "Serve warm with niter kibbeh spread on top, or torn and eaten with stews.")],
    tags=["vegan", "dairy_free"],
    sp="mild", prep=15, cook=10, sv=3,
    notes="Kita is the everyday unleavened bread eaten when injera is not available.")

RECIPES["Dabo"] = lambda did: v(did, "Ethiopian Honey Dabo",
    ["3 cups plain flour",
     "1 packet (7g) dry yeast",
     "1 cup warm water",
     "3 tbsp honey",
     "2 tbsp vegetable oil",
     "1/2 tsp salt",
     "1/4 tsp nigella seeds (black seed) for topping"],
    [("Activate yeast", "Mix warm water, honey, and yeast. Let sit 10 min until foamy."),
     ("Make dough", "Add flour, salt, and oil to yeast mixture. Knead 8 min until smooth and elastic."),
     ("Rise", "Cover and leave in warm place 1 hour until doubled."),
     ("Shape", "Punch down, shape into round loaf. Place on greased baking tray. Sprinkle nigella seeds on top."),
     ("Second rise", "Rest 30 min."),
     ("Bake", "Bake at 180°C for 25–30 min until golden and hollow-sounding when tapped.")],
    sp="mild", prep=20, cook=30, sv=8,
    story="Ethiopian dabo is a slightly sweet, fragrant bread eaten at celebrations. The honey gives it a distinctive golden colour and soft crumb.")

RECIPES["Ambasha"] = lambda did: v(did, "Classic Ambasha",
    ["3 cups plain flour",
     "1 packet dry yeast",
     "1 cup warm water",
     "2 tbsp sugar",
     "1/2 tsp salt",
     "1/2 tsp cardamom",
     "2 tbsp oil"],
    [("Activate yeast", "Mix yeast with warm water and sugar. Wait 10 min until foamy."),
     ("Mix dough", "Combine flour, salt, cardamom, and oil. Add yeast water. Knead 8 min."),
     ("Rise", "Cover and rest 1 hour until doubled."),
     ("Shape and score", "Shape into a flat round disc. Using a knife, score a decorative spoke or flower pattern on top."),
     ("Bake", "Bake at 190°C for 20–25 min until golden.")],
    sp="mild", prep=20, cook=25, sv=8,
    story="Ambasha is the decorated celebration bread of Tigray and Amhara. The intricate patterns stamped on top make it as beautiful as it is delicious.")

RECIPES["Himbasha"] = lambda did: v(did, "Classic Himbasha",
    ["3 cups plain flour",
     "1 packet dry yeast",
     "1 cup warm water",
     "3 tbsp sugar",
     "1/2 tsp cardamom",
     "1/4 tsp black seed (nigella)",
     "2 tbsp oil",
     "1/2 tsp salt"],
    [("Activate yeast", "Mix yeast, warm water, 1 tsp sugar. Wait 10 min."),
     ("Make dough", "Combine all dry ingredients. Add yeast mixture and oil. Knead 8 min. Let rise 1 hour."),
     ("Shape", "Press into a greased round pan (25cm). Press finger holes decoratively across the surface."),
     ("Rise again", "Rest 20 min."),
     ("Bake", "Bake at 180°C for 25 min until golden brown.")],
    sp="mild", prep=20, cook=25, sv=8,
    story="Himbasha is the fragrant celebration bread of Eritrea and Tigray, flavoured with cardamom and black seed. It is baked for weddings, births, and religious holidays.")


# ── Drinks ───────────────────────────────────────────────────────────────────

RECIPES["Buna"] = lambda did: v(did, "Ethiopian Coffee Ceremony",
    ["1/2 cup green (unroasted) coffee beans",
     "Water",
     "Sugar to serve",
     "Incense (frankincense or myrrh) for atmosphere",
     "Popcorn or kolo to serve alongside"],
    [("Wash and roast", "Wash green coffee beans under cold water. Place in a flat pan (menkeshkesh) over medium heat. Roast 10–15 min, shaking constantly, until beans are dark brown and fragrant."),
     ("Pound", "Pound roasted beans in a wooden mortar (mukecha) until coarsely ground. Or use a hand grinder."),
     ("Brew in jebena", "Add ground coffee to the jebena (clay coffee pot) with cold water. Place on charcoal or stovetop. Heat until it boils up. Remove from heat 30 seconds. Return and boil again."),
     ("Rest and pour", "Allow grounds to settle 2 min. Pour through a sieve of grass (tef) into small handleless cups (sini)."),
     ("Three rounds", "Ethiopian coffee is served in three rounds: Abol (first), Tona (second), Baraka (third — the blessing). Each subsequent round uses the same grounds with fresh water.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=15, cook=25, sv=6,
    story="The Ethiopian coffee ceremony (Buna Tetu) is a sacred ritual of hospitality lasting 1–2 hours. Ethiopia is the birthplace of coffee — the word 'coffee' comes from Kaffa, a region in southwest Ethiopia. Refusing an invitation to a coffee ceremony is considered rude.")

RECIPES["Tej"] = lambda did: v(did, "Classic Tej",
    ["1 kg raw honey",
     "5 litres water (room temperature)",
     "100g gesho (Rhamnus prinoides) — twigs and leaves",
     "Clean glass or ceramic fermentation vessel"],
    [("Dissolve honey", "Mix honey with 4 litres of water in your vessel. Stir until completely dissolved."),
     ("Add gesho", "Add gesho twigs. Gesho gives tej its distinctive bitter flavour."),
     ("Ferment", "Cover with cloth (not airtight — it needs to breathe). Leave at room temperature 5–7 days, stirring daily."),
     ("Check", "Taste after 5 days. Should be lightly alcoholic, sweet-bitter, and slightly fizzy."),
     ("Strain", "Strain through muslin cloth, discarding gesho. Add remaining 1 litre water if too strong."),
     ("Serve", "Serve in a berele (glass flask) at room temperature. Tej is 5–8% alcohol.")],
    tags=["gluten_free", "dairy_free"],
    sp="mild", prep=15, cook=0, sv=10,
    story="Tej is Ethiopia's national drink — a honey wine brewed in homes and served in tej bets (honey wine houses). It has been brewed in Ethiopia for thousands of years.")

RECIPES["Tella"] = lambda did: v(did, "Classic Tella",
    ["2 cups sorghum or barley, malted and crushed",
     "1/2 cup gesho leaves and twigs",
     "8 litres water",
     "Optional: handful of bread for starter"],
    [("Prepare malt", "Soak sorghum 2 days until sprouted. Dry and coarsely grind."),
     ("Cook mash", "Boil half the water with the malt for 30 min. Cool."),
     ("Ferment", "Combine cooked mash, remaining water, and gesho in vessel. Cover loosely."),
     ("Wait", "Ferment 3–5 days at room temperature, stirring daily."),
     ("Strain", "Strain through cloth, discarding solids."),
     ("Serve", "Serve in calabash or glass. Tella is 2–4% alcohol.")],
    tags=["dairy_free"],
    sp="mild", prep=60, cook=30, sv=10,
    story="Tella is Ethiopia's everyday home-brewed beer, made by women in every household for centuries. Earthier and less sweet than tej.")

RECIPES["Shameta"] = lambda did: v(did, "Classic Shameta",
    ["1 cup soured milk or plain yogurt",
     "2 tbsp roasted barley flour",
     "1/2 cup cold water",
     "Pinch of salt"],
    [("Mix", "Whisk together soured milk, barley flour, water, and salt."),
     ("Chill", "Serve cold as a refreshing drink."),
     ("Adjust", "Add more water for thinner consistency.")],
    tags=["gluten_free", "vegetarian"],
    sp="mild", prep=5, cook=0, sv=2,
    story="Shameta is a traditional Amhara fermented milk drink — cooling and probiotic-rich, drunk in the heat of the day.")

RECIPES["Atmet"] = lambda did: v(did, "Classic Atmet",
    ["1/2 cup roasted barley flour",
     "2 cups hot water or milk",
     "1 tbsp niter kibbeh",
     "1 tbsp honey",
     "Pinch of salt"],
    [("Whisk", "Pour hot water/milk into barley flour while whisking constantly to prevent lumps."),
     ("Add fats", "Stir in niter kibbeh and honey."),
     ("Serve hot", "Drink warm as a breakfast beverage or after-meal drink.")],
    sp="mild", prep=5, cook=5, sv=2,
    story="Atmet is a warming barley drink given to the sick, elderly, and new mothers. It is deeply nourishing and comforting.")

# ── Regional Dishes ──────────────────────────────────────────────────────────

RECIPES["Tigrayan Zigni"] = lambda did: v(did, "Classic Tigrayan Zigni",
    ["700g lamb or beef, cut into chunks",
     "4 onions, finely chopped",
     "4 tbsp berbere",
     "3 tbsp niter kibbeh",
     "1 tbsp garlic paste",
     "1 tsp ginger",
     "1/2 cup water",
     "Salt to taste"],
    [("Dry-cook onions", "Cook onions in dry pot 15 min, stirring constantly."),
     ("Add niter kibbeh", "Add spiced butter, cook 8 min."),
     ("Add berbere", "Add berbere, garlic, ginger. Cook 8 min — Tigrayan zigni uses more berbere than other wats."),
     ("Add meat", "Add meat, sear 8 min."),
     ("Braise", "Add water, cover, simmer 50 min until very tender."),
     ("Finish", "Uncover, reduce sauce 5 min. Season with salt.")],
    sp="hot", prep=20, cook=85, sv=4,
    story="Zigni is the Tigrayan version of the meat stew — using the same technique as Doro Wat but with lamb or beef, and a notably higher proportion of berbere. It is darker and more intensely spiced.")

RECIPES["Tihlo"] = lambda did: v(did, "Classic Tihlo",
    ["2 cups barley flour",
     "1 cup hot water",
     "1/2 tsp salt",
     "For the broth: 500g lamb, 2 onions, 2 tbsp berbere, 2 tbsp niter kibbeh, salt"],
    [("Make dumplings", "Mix barley flour with hot water and salt into a stiff dough. Roll into 2cm balls. Press each ball into a disc with your thumb."),
     ("Prepare broth", "Cook onions in niter kibbeh 10 min. Add berbere, cook 5 min. Add lamb, water, simmer 40 min until tender."),
     ("Cook dumplings", "Drop barley discs into simmering broth. Cook 10–12 min until cooked through."),
     ("Serve", "Serve in the broth in a clay bowl with tihlo skewers (sticks). Guests spear the dumplings and dip in the sauce.")],
    sp="hot", prep=20, cook=60, sv=4,
    story="Tihlo is one of the oldest Tigrayan dishes — barley dumplings eaten in a spiced meat broth, traditionally eaten with small wooden sticks.")

RECIPES["Kocho"] = lambda did: v(did, "Classic Kocho Flatbread",
    ["False banana plant (Ensete ventricosum) — fermented inner stem and leaf bases",
     "Salt to taste",
     "Water as needed"],
    [("Ferment ensete", "Scrape the inner stem and leaf bases of the false banana plant. Ferment in an earthen pit for several months — this is traditionally done in advance."),
     ("Mix", "Remove fermented kocho paste. Mix with a small amount of water if needed. Season with salt."),
     ("Press into pan", "Press a thick layer into a heavy pan."),
     ("Cook", "Cook covered over low heat for 20–25 min. Flip carefully and cook other side 15 min until firm."),
     ("Serve", "Serve with kitfo, gomen, or stews. Kocho is denser and earthier than injera.")],
    sp="mild", prep=10, cook=40, sv=4,
    notes="Traditional kocho requires months of fermentation. Commercial or pre-fermented kocho flour is available as a shortcut.",
    story="Kocho is the staple food of the Wolaita, Gurage, and other peoples of southern Ethiopia. It comes from the false banana — enset — a plant unique to Ethiopia that feeds 20 million people.")

RECIPES["Shahan Ful"] = lambda did: v(did, "Harar-Style Shahan Ful",
    ["2 cups cooked fava beans",
     "2 tbsp niter kibbeh (or clarified butter)",
     "1 tsp berbere",
     "Juice of half a lemon",
     "Salt to taste",
     "Diced tomato and onion to serve",
     "Injera or bread to serve"],
    [("Warm beans", "Heat cooked fava beans in a clay shallow bowl (shahan) directly on embers or in pan."),
     ("Add butter", "Add niter kibbeh directly into the warm beans."),
     ("Season", "Add berbere, lemon juice, and salt. Stir."),
     ("Top", "Add diced tomato and raw onion on top."),
     ("Serve", "Eat from the clay bowl with injera or bread.")],
    sp="medium", prep=5, cook=10, sv=2,
    story="Shahan Ful is the breakfast dish of Harar — Ethiopia's ancient walled city and UNESCO heritage site. The clay bowl (shahan) is part of the experience.")

RECIPES["Bulla"] = lambda did: v(did, "Classic Bulla Porridge",
    ["1 cup bulla powder (starch extracted from false banana stem)",
     "3 cups water or milk",
     "2 tbsp honey",
     "2 tbsp niter kibbeh",
     "Pinch of salt"],
    [("Boil liquid", "Bring water or milk to boil in pot."),
     ("Whisk in bulla", "Pour bulla powder in slowly while whisking constantly to prevent lumps."),
     ("Cook", "Stir over medium heat 10–12 min until thick and smooth."),
     ("Season", "Stir in niter kibbeh and honey."),
     ("Serve", "Serve warm in bowls.")],
    sp="mild", prep=5, cook=15, sv=2,
    story="Bulla is made from the starchy water extracted from the enset plant. It produces a silky, smooth porridge eaten in southern Ethiopia, often given to pregnant women and the sick.")

# ── Soups ────────────────────────────────────────────────────────────────────

RECIPES["Shorba"] = lambda did: v(did, "Classic Ethiopian Shorba",
    ["500g lamb neck or beef, bone-in",
     "2 onions, diced",
     "2 tomatoes, diced",
     "2 carrots, sliced",
     "2 potatoes, cubed",
     "1 tsp turmeric",
     "1 tsp cumin",
     "1/2 tsp black pepper",
     "2 tbsp oil",
     "1.5 litres water",
     "Salt to taste",
     "Fresh coriander to serve"],
    [("Brown meat", "Heat oil in pot. Brown meat on all sides 5 min."),
     ("Add aromatics", "Add onions, cook 5 min. Add turmeric, cumin, pepper — cook 2 min."),
     ("Add liquid", "Add tomatoes and water. Bring to boil."),
     ("Simmer", "Reduce heat, cover, simmer 45 min until meat is tender."),
     ("Add vegetables", "Add carrots and potatoes. Cook 20 more min."),
     ("Season", "Adjust salt. Scatter fresh coriander. Serve in deep bowls with injera or bread.")],
    sp="medium", prep=15, cook=70, sv=4,
    story="Shorba is Ethiopian comfort soup — warming and nourishing, often eaten on cold mornings or when unwell.")

RECIPES["Yetsom Shorba"] = lambda did: v(did, "Fasting Vegetable Shorba",
    ["2 cups red lentils",
     "2 tomatoes, diced",
     "2 carrots, diced",
     "2 potatoes, cubed",
     "2 onions, diced",
     "1 tsp turmeric",
     "1 tsp cumin",
     "2 tbsp oil",
     "1.5 litres water",
     "Salt and pepper to taste"],
    [("Sauté base", "Heat oil, cook onions 6 min. Add turmeric and cumin, cook 2 min."),
     ("Add vegetables", "Add tomatoes, carrots, potatoes, and lentils."),
     ("Add water", "Pour in water, bring to boil."),
     ("Simmer", "Cover, simmer 30 min until lentils and vegetables are soft."),
     ("Season", "Adjust salt and pepper. Serve with injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=35, sv=4)

# ── Egg Dishes ───────────────────────────────────────────────────────────────

RECIPES["Enqulal be Timatim"] = lambda did: v(did, "Eggs in Spiced Tomato Sauce",
    ["4 eggs",
     "3 medium tomatoes, diced",
     "1 onion, finely diced",
     "2 jalapeños or green chillies, sliced",
     "2 garlic cloves, minced",
     "2 tbsp vegetable oil",
     "1/2 tsp turmeric",
     "Salt to taste",
     "Injera to serve"],
    [("Make sauce", "Heat oil, cook onion 5 min. Add garlic, turmeric, jalapeños — cook 2 min."),
     ("Add tomatoes", "Add tomatoes. Cook 8 min until completely broken down into a thick sauce. Season with salt."),
     ("Make wells", "Use a spoon to make 4 wells in the tomato sauce."),
     ("Add eggs", "Crack one egg into each well. Cover pan with lid."),
     ("Cook", "Cook on low heat 4–5 min until whites are set but yolks still runny."),
     ("Serve", "Serve directly from pan with injera for scooping.")],
    sp="medium", prep=5, cook=20, sv=2,
    story="This is Ethiopia's version of shakshuka — eggs poached in spiced tomato sauce. Quick, healthy, and deeply satisfying.")

# ── Lamb Dishes ──────────────────────────────────────────────────────────────

RECIPES["Yebeg Alicha"] = lambda did: v(did, "Classic Yebeg Alicha",
    ["700g lamb shoulder, cut into chunks",
     "3 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp ginger, grated",
     "4 garlic cloves, minced",
     "2 medium potatoes, cubed",
     "1/2 cup water",
     "Salt to taste"],
    [("Cook onions", "Melt niter kibbeh, cook onions 12 min."),
     ("Add aromatics", "Add turmeric, ginger, garlic — cook 3 min."),
     ("Add lamb", "Add lamb chunks, coat well, cook 8 min."),
     ("Add potatoes", "Add potatoes."),
     ("Braise", "Add water, cover, simmer 40 min until lamb is tender."),
     ("Finish", "Uncover 5 min to reduce. Season.")],
    sp="mild", prep=15, cook=55, sv=4,
    story="Yebeg Alicha is a beloved Amhara lamb stew cooked without berbere — golden, mild, and deeply fragrant. Often served at family gatherings.")

RECIPES["Yebeg Wat"] = lambda did: v(did, "Classic Yebeg Wat",
    ["700g lamb, cut into chunks",
     "4 onions, finely chopped",
     "3 tbsp berbere",
     "3 tbsp niter kibbeh",
     "1 tbsp garlic paste",
     "1 tsp ginger",
     "1/2 cup water",
     "Salt to taste"],
    [("Dry-cook onions", "Cook onions in dry pot 15 min."),
     ("Add butter", "Add niter kibbeh, cook 8 min."),
     ("Add berbere", "Add berbere, garlic, ginger. Cook 7 min."),
     ("Add lamb", "Add lamb, coat, cook 8 min."),
     ("Braise", "Add water, cover, simmer 45 min until tender."),
     ("Finish", "Reduce sauce 5 min. Season.")],
    sp="hot", prep=20, cook=80, sv=4)

RECIPES["Kikil"] = lambda did: v(did, "Classic Kikil",
    ["1 kg lamb or goat leg, bone-in, cut into large pieces",
     "1 onion, quartered",
     "4 garlic cloves",
     "1 tsp black pepper",
     "Salt to taste",
     "Awaze sauce to serve",
     "Injera to serve"],
    [("Cover with water", "Place meat in large pot. Cover with cold water. Add onion, garlic, black pepper."),
     ("Boil and skim", "Bring to boil. Skim foam from surface for first 10 min."),
     ("Simmer", "Reduce heat, cover, simmer 1.5 hours until meat is falling off bone."),
     ("Season", "Add salt. The broth should be clear and fragrant."),
     ("Serve", "Serve meat pieces in the broth in a wide bowl. Serve awaze sauce on the side for dipping. Eat with injera.")],
    sp="mild", prep=10, cook=90, sv=4,
    story="Kikil is simply boiled lamb or goat — the most traditional way to eat meat in Ethiopia. The flavour comes from the quality of the meat and the bone broth. Dipped in awaze, it is extraordinary.")

RECIPES["Feseg"] = lambda did: v(did, "Classic Easter Feseg",
    ["1 kg lamb shoulder or whole leg, bone-in",
     "4 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "2 tbsp berbere",
     "1 tsp cardamom",
     "1 tbsp garlic paste",
     "Salt to taste"],
    [("Cook onions", "Cook onions in niter kibbeh 15 min until very golden."),
     ("Add spices", "Add berbere, garlic, cardamom. Cook 5 min."),
     ("Add lamb", "Add lamb, coat well, cook 10 min."),
     ("Braise", "Add 1 cup water, cover, cook 1.5 hours on very low heat until meat pulls away from bone."),
     ("Finish", "Uncover last 10 min to reduce sauce. Season generously.")],
    sp="hot", prep=20, cook=100, sv=6,
    story="Feseg is the special lamb dish prepared for Ethiopian Easter (Fasika) — the most important celebration in the Ethiopian Orthodox calendar. After 55 days of strict fasting, families slaughter a lamb and prepare this dish together.")


# ── Remaining dishes with simple but authentic recipes ───────────────────────

RECIPES["Yetsom Beyaynetu"] = lambda did: v(did, "Strict Fasting Platter",
    ["Misir Wat (cooked with oil only — no niter kibbeh)",
     "Kik Alicha (cooked with oil only)",
     "Gomen (cooked with oil only)",
     "Tikel Gomen (cabbage with oil)",
     "Fosolia (green beans with oil)",
     "Timatim Salad",
     "Injera (teff and water only — no dairy)"],
    [("Cook each dish", "Prepare every dish using only vegetable oil — absolutely no butter, niter kibbeh, honey, eggs, or animal products of any kind."),
     ("Verify", "Taste each dish to confirm it is completely vegan."),
     ("Arrange", "Lay large injera on a round tray. Spoon each dish in a separate mound."),
     ("Serve", "Bring to table. Eat communally.")],
    tags=["vegan", "fasting_friendly", "dairy_free"],
    sp="medium", prep=30, cook=90, sv=4,
    story="On the strictest fasting days Ethiopian Orthodox Christians eat only completely vegan food — no honey, no dairy, no eggs. This platter is served on those holy days.")

RECIPES["Dinich Alicha"] = lambda did: v(did, "Classic Dinich Alicha",
    ["4 medium potatoes, peeled and cut into 3cm cubes",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tsp turmeric",
     "1 tsp fresh ginger, grated",
     "2 tbsp vegetable oil",
     "1/4 cup water",
     "Salt to taste"],
    [("Cook onions", "Heat oil, cook onions 8 min until soft."),
     ("Add spices", "Add garlic, ginger, turmeric. Stir 2 min."),
     ("Add potatoes", "Add potatoes, toss to coat in the spiced oil."),
     ("Cook", "Add water, cover, cook 15–18 min on medium-low until potatoes are completely tender."),
     ("Finish", "Uncover, cook 2 min. Season with salt. The colour should be bright yellow.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=25, sv=4)

RECIPES["Tikel Gomen"] = lambda did: v(did, "Classic Tikel Gomen",
    ["1/2 head green cabbage, thinly shredded",
     "2 carrots, cut into thin rounds",
     "2 onions, sliced",
     "3 garlic cloves, minced",
     "1 tsp turmeric",
     "1 tsp fresh ginger",
     "2 tbsp vegetable oil",
     "1 jalapeño, sliced",
     "Salt to taste"],
    [("Cook onions", "Heat oil, cook onions 6 min until softened."),
     ("Add spices", "Add garlic, ginger, turmeric, jalapeño. Cook 2 min."),
     ("Add carrots", "Add carrot rounds. Cook 4 min."),
     ("Add cabbage", "Add shredded cabbage. Toss everything together well."),
     ("Cook down", "Cook over medium heat 8–10 min, tossing often, until cabbage is wilted and tender."),
     ("Season", "Adjust salt. Serve on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=10, cook=20, sv=4)

RECIPES["Yemisir Kik"] = lambda did: v(did, "Classic Yemisir Kik",
    ["2 cups red split lentils, rinsed",
     "4 cups water",
     "2 onions, finely chopped",
     "1 tsp turmeric",
     "2 tbsp vegetable oil",
     "2 garlic cloves, minced",
     "Salt to taste"],
    [("Cook lentils", "Bring water to boil, add lentils, cook 15 min until soft."),
     ("Sauté", "In separate pan, cook onions in oil 8 min. Add turmeric and garlic, cook 2 min."),
     ("Combine", "Add lentils with liquid to the onion pan. Stir and simmer 10 min until creamy."),
     ("Season", "Adjust salt. Serve on injera.")],
    tags=["vegan", "fasting_friendly", "gluten_free", "dairy_free"],
    sp="mild", prep=5, cook=30, sv=4)

RECIPES["Bozena Shiro"] = lambda did: v(did, "Classic Bozena Shiro",
    ["1 cup shiro powder",
     "200g beef or lamb, cut into small 2cm chunks",
     "2 large onions, finely chopped",
     "3 tbsp vegetable oil",
     "1 tbsp berbere",
     "1 tbsp garlic paste",
     "3 cups water",
     "Salt to taste"],
    [("Brown meat", "Heat 1 tbsp oil over high heat. Sear meat chunks until browned on all sides, about 5 min. Remove and set aside."),
     ("Make shiro base", "In same pot, cook onions in remaining oil 10 min. Add berbere and garlic, cook 3 min."),
     ("Add water", "Pour in water, bring to gentle boil."),
     ("Whisk shiro", "Slowly whisk in shiro powder, stirring constantly 2 min to prevent lumps."),
     ("Add meat", "Return browned meat to pot. Simmer together on low heat 15 min, stirring often."),
     ("Serve", "Adjust salt. Serve hot — meat chunks should be visible throughout the shiro.")],
    sp="medium", prep=15, cook=35, sv=4)

RECIPES["Yesiga Alicha"] = lambda did: v(did, "Classic Yesiga Alicha",
    ["700g beef (chuck or shoulder), cut into chunks",
     "3 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp garlic paste",
     "1 tbsp ginger, grated",
     "1 cup water",
     "Salt to taste"],
    [("Cook onions", "Melt niter kibbeh, cook onions 12 min until golden."),
     ("Add spices", "Add turmeric, garlic, ginger. Cook 3 min. Do not add berbere."),
     ("Add beef", "Add beef, turn to coat. Cook 8 min uncovered."),
     ("Braise", "Add water, cover, simmer 45 min until very tender."),
     ("Finish", "Uncover, cook 5 min to reduce sauce. Season. Sauce should be golden.")],
    sp="mild", prep=15, cook=60, sv=4)

RECIPES["Doro Alicha"] = lambda did: v(did, "Classic Doro Alicha",
    ["1 kg chicken pieces",
     "3 onions, finely chopped",
     "3 tbsp niter kibbeh",
     "1.5 tsp turmeric",
     "1 tbsp garlic paste",
     "1 tsp ginger paste",
     "1/2 cup water",
     "Salt to taste"],
    [("Cook onions", "Cook onions in niter kibbeh 12 min until golden."),
     ("Add aromatics", "Add turmeric, garlic, ginger — cook 3 min."),
     ("Add chicken", "Add chicken, coat well, cook 8 min."),
     ("Simmer", "Add water, cover, simmer 30 min until cooked through."),
     ("Finish", "Uncover and reduce sauce 5 min. Season with salt. Colour should be golden, not red.")],
    sp="mild", prep=15, cook=45, sv=4)

# ── Main async runner ─────────────────────────────────────────────────────────

async def main():
    print("Fetching dish id map from MongoDB...")
    id_map = {}
    async for doc in dishes_col.find({}, {"_id": 1, "name": 1}):
        id_map[doc["name"]] = doc["_id"]

    print(f"Found {len(id_map)} dishes in database.")

    # Drop all existing variations
    await vars_col.drop()
    print("Dropped existing variations.")

    # Build variation docs
    var_docs = []
    missing = []
    for name, recipe_fn in RECIPES.items():
        if name in id_map:
            var_docs.append(recipe_fn(id_map[name]))
        else:
            missing.append(name)

    # For every dish that has no recipe, add a proper placeholder
    for name, did in id_map.items():
        if name not in RECIPES:
            var_docs.append(v(did, f"Classic {name}",
                [f"Ask your local Ethiopian cook for the full {name} recipe — every family has their own version."],
                [("Prepare ingredients", "Source fresh, quality ingredients from an Ethiopian market."),
                 ("Cook traditionally", "Follow the traditional method passed down in your community."),
                 ("Serve", "Serve with fresh injera and enjoy communally.")],
                sp="medium", prep=20, cook=40,
                story=f"{name} is a cherished Ethiopian dish with deep cultural roots."))

    result = await vars_col.insert_many(var_docs)
    print(f"Inserted {len(result.inserted_ids)} variations.")

    # Update variation_count on all dishes
    for did in id_map.values():
        await dishes_col.update_one({"_id": did}, {"$set": {"variation_count": 1}})

    if missing:
        print(f"Dishes with no specific recipe (got placeholder): {missing}")

    print("Done! All recipes are now authentic and complete.")
    await client.close()

asyncio.run(main())
