"""Run once: python seed_data.py  — populates MongoDB with Ethiopian recipes."""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
from dotenv import load_dotenv
import os

load_dotenv()

client = AsyncIOMotorClient(os.getenv("MONGO_URL", "mongodb://localhost:27017"))
db = client[os.getenv("DB_NAME", "megeb")]

def r(name, desc, img, prep, cook, servings, ingredients, steps, youtube_url=None):
    return {
        "name": name, "description": desc, "nationality": "Ethiopian",
        "image": img, "prep_time": prep, "cook_time": cook, "servings": servings,
        "author_name": "Megeb Kitchen", "ingredients": ingredients,
        "steps": [{"title": t, "text": x} for t, x in steps],
        "youtube_url": youtube_url,
        "search_count": 0, "created_at": datetime.now(timezone.utc),
    }

RECIPES = [
    r("Doro Wat",
      "Ethiopia's national dish — deeply spiced chicken stew simmered with berbere and niter kibbeh, served on injera.",
      "https://images.unsplash.com/photo-1584270354949-56a348646bfe?w=800&q=80",
      "30 min", "1 hr 30 min", "4",
      ["1 whole chicken, cut into pieces","4 large onions, finely chopped","1/3 cup niter kibbeh",
       "3 tbsp berbere spice","4 hard-boiled eggs","1 tbsp garlic paste","Salt","Injera to serve"],
      [("Dry-cook onions","Cook chopped onions with no oil for 15 min, stirring constantly."),
       ("Add niter kibbeh","Add spiced butter, cook 10 min until golden."),
       ("Add berbere","Add berbere and garlic, cook 5 min."),
       ("Add chicken","Add chicken pieces, coat well, cook 30 min."),
       ("Add eggs","Add pierced hard-boiled eggs, simmer 20 min until sauce is thick."),
       ("Serve","Serve hot over fresh injera.")],
      "https://www.youtube.com/watch?v=wO_-xP2k9yE"),

    r("Tibs",
      "Tender sautéed beef or lamb with jalapeños, rosemary, onions, and tomatoes.",
      "https://images.unsplash.com/photo-1585238341710-4700bde7e3a0?w=800&q=80",
      "15 min", "20 min", "3",
      ["500g beef or lamb, cubed","2 onions, sliced","2 jalapeños","2 tomatoes",
       "2 tbsp niter kibbeh","1 sprig rosemary","Salt and pepper"],
      [("Heat pan","Heat pan over high heat, add niter kibbeh."),
       ("Sear meat","Sear meat without stirring for 3–4 min."),
       ("Add aromatics","Add onions, jalapeños, rosemary. Toss 5 min."),
       ("Finish","Add tomatoes, cook 5 min. Season and serve.")],
      "https://www.youtube.com/watch?v=Oi0wr97sZfo"),

    r("Shiro Wat",
      "Creamy spiced chickpea flour stew — cornerstone of Ethiopian fasting cuisine.",
      "https://images.unsplash.com/photo-1645142601528-1f33f27cc619?w=800&q=80",
      "10 min", "25 min", "4",
      ["1 cup shiro powder","2 onions, finely chopped","3 cups water",
       "3 tbsp oil","1 tbsp garlic paste","1 tbsp berbere","Salt"],
      [("Cook onions","Heat oil, cook onions 10 min until golden."),
       ("Add spices","Add garlic and berbere, cook 2 min."),
       ("Add water","Pour in water, bring to gentle boil."),
       ("Whisk shiro","Slowly whisk in shiro powder to avoid lumps."),
       ("Simmer","Simmer 10–15 min stirring until thick. Season.")],
      "https://www.youtube.com/watch?v=MkNjIz0kZQQ"),

    r("Injera",
      "The spongy sourdough flatbread that is the foundation of every Ethiopian meal.",
      "https://images.unsplash.com/photo-1628840042765-356cda07f4ee?w=800&q=80",
      "5 min + 2 days ferment", "30 min", "8",
      ["3 cups teff flour","3 cups water","1/2 tsp salt"],
      [("Mix batter","Combine teff flour and water. Stir well."),
       ("Ferment","Cover and leave at room temperature 2–3 days until bubbly and sour."),
       ("Add salt","Stir in salt before cooking."),
       ("Cook","Pour thin layer onto hot non-stick pan. Cover and cook 2 min until bubbles form and top is dry. Do not flip."),
       ("Cool","Slide onto a rack. Cool before stacking.")],
      "https://www.youtube.com/watch?v=dSJxPGwOqgQ"),

    r("Kitfo",
      "Ethiopian steak tartare — minced lean beef seasoned with mitmita and niter kibbeh.",
      "https://images.unsplash.com/photo-1568043666682-3baacb822e72?w=800&q=80",
      "20 min", "5 min", "2",
      ["400g very lean beef, minced","2 tbsp niter kibbeh","1 tsp mitmita","1/2 tsp cardamom",
       "Salt","Ayib (Ethiopian cottage cheese) to serve","Injera or kita to serve"],
      [("Season butter","Warm niter kibbeh gently, stir in mitmita and cardamom."),
       ("Mix beef","Toss minced beef with spiced butter until fully coated."),
       ("Serve","Serve immediately with ayib and injera. For leb leb (medium), flash-cook in pan 2 min.")],
      "https://www.youtube.com/watch?v=kM6b8x0eZLU"),

    r("Firfir",
      "Torn injera soaked in spiced berbere-tomato sauce. Bold, warming, and quick.",
      "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=800&q=80",
      "10 min", "20 min", "2",
      ["2 large onions","1/4 cup oil","2 tbsp berbere","1 tbsp garlic paste",
       "2 tomatoes, diced","1 cup water","Salt","2 pieces injera, torn"],
      [("Cook onions","Heat oil, cook onions 10–15 min until golden."),
       ("Add spices","Add garlic and berbere, cook 5 min."),
       ("Simmer sauce","Add tomatoes and water, simmer 10 min. Season."),
       ("Mix injera","Fold in torn injera, coat each piece in sauce. Serve warm.")],
      "https://www.youtube.com/watch?v=qEb40xP_9pE"),

    r("Misir Wat",
      "Red lentils slow-cooked in a rich berbere sauce — a staple of fasting days.",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      "10 min", "40 min", "4",
      ["2 cups red lentils","3 onions, finely chopped","3 tbsp berbere","2 tbsp oil",
       "1 tbsp garlic paste","1 tsp ginger","4 cups water","Salt"],
      [("Cook onions","Dry-cook onions 10 min, then add oil and cook 5 more min."),
       ("Add spices","Add berbere, garlic, ginger. Cook 5 min."),
       ("Add lentils","Add rinsed lentils and water. Bring to boil."),
       ("Simmer","Reduce heat, simmer 25 min stirring until thick and creamy. Season.")],
      "https://www.youtube.com/watch?v=2i82HNm_tQI"),

    r("Gomen",
      "Ethiopian collard greens sautéed with garlic, onion, and mild spices.",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      "15 min", "25 min", "4",
      ["1 large bunch collard greens, chopped","2 onions, sliced","4 garlic cloves",
       "1 tbsp ginger","3 tbsp oil","1 jalapeño","Salt"],
      [("Blanch greens","Boil collards 5 min, drain and squeeze dry."),
       ("Sauté aromatics","Heat oil, cook onions 8 min. Add garlic and ginger."),
       ("Combine","Add greens and jalapeño, toss well. Cook 10 min. Season.")],
      "https://www.youtube.com/watch?v=VqzDqJhN0fc"),

    r("Atkilt Wat",
      "Spiced cabbage, carrot, and potato stew — mild, comforting, and vegan.",
      "https://images.unsplash.com/photo-1599599810694-13b47a1fdd60?w=800&q=80",
      "15 min", "30 min", "4",
      ["1/2 head cabbage, chopped","3 carrots, sliced","3 potatoes, cubed","2 onions",
       "1 tsp turmeric","1 tsp cumin","3 tbsp oil","Salt"],
      [("Cook onions","Heat oil, cook onions 8 min."),
       ("Add spices","Add turmeric and cumin, cook 2 min."),
       ("Add vegetables","Add potatoes and carrots, cook 10 min. Add cabbage."),
       ("Finish","Cover and cook 15 min until tender. Season.")],
      "https://www.youtube.com/watch?v=kqJxBLBWLkc"),

    r("Beyaynetu",
      "The grand vegetarian platter — a colourful spread of fasting dishes arranged on injera.",
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
      "30 min", "1 hr", "4",
      ["Misir wat (red lentils)","Shiro wat","Gomen (collard greens)","Atkilt wat",
       "Timatim salad","Fosolia (green beans)","Injera"],
      [("Prepare each dish","Cook misir wat, shiro, gomen, atkilt, and fosolia separately."),
       ("Arrange","Line a large injera on a tray. Spoon each dish in separate mounds around the injera."),
       ("Serve","Tear pieces of injera and scoop up the stews. Eat communally.")],
      "https://www.youtube.com/watch?v=PdPlxNZVDcg"),

    r("Fosolia",
      "Ethiopian green beans and carrots sautéed with garlic and ginger.",
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
      "10 min", "20 min", "4",
      ["300g green beans","2 carrots, julienned","2 onions","3 garlic cloves","2 tbsp oil","Salt"],
      [("Sauté","Heat oil, cook onions 5 min, add garlic."),
       ("Add veg","Add beans and carrots, cook 12 min until tender. Season.")],
      "https://www.youtube.com/watch?v=NfNvQKl5kro"),

    r("Timatim Salad",
      "Fresh Ethiopian tomato and jalapeño salad with lemon and herbs.",
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
      "10 min", "0 min", "4",
      ["4 tomatoes, diced","1 red onion, diced","2 jalapeños, sliced","Juice of 1 lemon","2 tbsp oil","Salt"],
      [("Mix","Combine all ingredients."),
       ("Rest","Let sit 10 min before serving.")],
      "https://www.youtube.com/watch?v=R89XAoLT1Eo"),

    r("Ayib",
      "Ethiopian fresh cottage cheese — mild and crumbly, served alongside spicy dishes.",
      "https://images.unsplash.com/photo-1452894895917-7c06b536ae48?w=800&q=80",
      "5 min", "20 min + drain", "6",
      ["2 litres whole milk","3 tbsp lemon juice or white vinegar","1/2 tsp salt"],
      [("Heat milk","Bring milk to near boil."),
       ("Curdle","Add lemon juice, stir gently. Curds will form."),
       ("Drain","Pour through cheesecloth, drain 1 hour. Salt and serve.")],
      "https://www.youtube.com/watch?v=Ij9h1ZRH5Rk"),

    r("Niter Kibbeh",
      "Ethiopian spiced clarified butter — the foundation of countless dishes.",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      "5 min", "30 min", "16",
      ["500g unsalted butter","1 onion, chopped","4 garlic cloves","1 tbsp ginger",
       "1/2 tsp turmeric","1/4 tsp cardamom","1 cinnamon stick","2 cloves"],
      [("Melt butter","Melt butter over low heat."),
       ("Add aromatics","Add all aromatics, simmer 20 min — do not boil."),
       ("Strain","Pour through fine sieve into a jar. Keeps 3 months refrigerated.")],
      "https://www.youtube.com/watch?v=K-x7IVT61vI"),

    r("Sambusa",
      "Crispy fried pastry triangles stuffed with spiced lentils or beef.",
      "https://images.unsplash.com/photo-1608897263797-ec2bea540042?w=800&q=80",
      "30 min", "20 min", "12",
      ["2 cups flour","Water and salt for dough","1 cup cooked lentils or minced beef",
       "1 onion, diced","2 jalapeños","1 tsp cumin","Oil for frying"],
      [("Make dough","Mix flour, salt, water to a firm dough. Rest 20 min."),
       ("Make filling","Cook onion, jalapeño, cumin with lentils or meat. Cool."),
       ("Shape","Roll dough thin, cut circles, fold into cones, fill, seal edges."),
       ("Fry","Deep-fry in hot oil until golden, 3–4 min. Drain.")],
      "https://www.youtube.com/watch?v=92q5qxiNhAA"),

    r("Kik Alicha",
      "Yellow split peas cooked with turmeric and garlic — mild and golden.",
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
      "10 min", "35 min", "4",
      ["2 cups yellow split peas","3 cups water","2 onions","1 tsp turmeric","3 tbsp oil","3 garlic cloves","Salt"],
      [("Cook peas","Boil split peas in water 20 min until soft."),
       ("Sauté","Cook onions in oil 8 min, add turmeric and garlic."),
       ("Combine","Add peas to onion mix, simmer 10 min. Mash slightly. Season.")],
      "https://www.youtube.com/watch?v=T3YqYIIKFo0"),

    r("Dulet",
      "Minced tripe, liver, and beef sautéed with spices — a bold Ethiopian offal dish.",
      "https://images.unsplash.com/photo-1585238341710-4700bde7e3a0?w=800&q=80",
      "20 min", "20 min", "3",
      ["200g tripe, minced","200g liver, minced","200g lean beef, minced",
       "2 onions","2 tbsp niter kibbeh","1 tbsp mitmita","1 jalapeño","Salt"],
      [("Cook onions","Sauté onions in niter kibbeh 8 min."),
       ("Add meats","Add tripe first (5 min), then beef (3 min), then liver (2 min)."),
       ("Season","Add mitmita, jalapeño, salt. Toss and serve with injera.")],
      "https://www.youtube.com/watch?v=BvY8BLbHKBk"),

    r("Quanta Firfir",
      "Dried beef strips rehydrated and mixed with injera in a spiced berbere sauce.",
      "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=800&q=80",
      "15 min", "25 min", "3",
      ["200g quanta (dried beef), soaked","2 onions","2 tbsp berbere","2 tbsp niter kibbeh",
       "1 tbsp garlic","Salt","2 pieces injera, torn"],
      [("Cook onions","Sauté onions in niter kibbeh 10 min."),
       ("Add beef","Add quanta and berbere, cook 10 min."),
       ("Add injera","Fold in torn injera, coat well. Serve hot.")],
      "https://www.youtube.com/watch?v=GqY4yxNkRvM"),

    r("Teff Porridge (Genfo)",
      "Thick teff porridge served with a well of niter kibbeh and berbere in the centre.",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      "5 min", "20 min", "2",
      ["1 cup teff flour","3 cups water","1/2 tsp salt","2 tbsp niter kibbeh","1 tsp berbere"],
      [("Boil water","Bring salted water to boil."),
       ("Whisk teff","Slowly whisk in teff flour. Stir constantly 15 min until very thick."),
       ("Serve","Mound in bowl, make a well in centre, fill with niter kibbeh and berbere.")],
      "https://www.youtube.com/watch?v=GhXXlW9XfQo"),

    r("Chechebsa",
      "Shredded flatbread (kita) tossed with niter kibbeh and berbere — a popular breakfast.",
      "https://images.unsplash.com/photo-1585518419759-ebb26f5d3e2d?w=800&q=80",
      "10 min", "15 min", "2",
      ["2 kita flatbreads (or thin injera)","3 tbsp niter kibbeh","1 tbsp berbere","Honey to serve"],
      [("Make kita","Cook thin flatbreads in dry pan, 2 min per side."),
       ("Shred","Tear into bite-size pieces."),
       ("Toss","Toss warm pieces with niter kibbeh and berbere until coated."),
       ("Serve","Drizzle with honey. Serve for breakfast.")],
      "https://www.youtube.com/watch?v=PZRc6RkMWZo"),

    r("Buticha",
      "Smooth chickpea dip seasoned with lemon, garlic, and jalapeño — served cold.",
      "https://images.unsplash.com/photo-1585707571428-4e211ae03e11?w=800&q=80",
      "10 min", "0 min", "4",
      ["2 cups cooked chickpeas","2 tbsp olive oil","Juice of 1 lemon","2 garlic cloves","1 jalapeño","Salt"],
      [("Blend","Blend all ingredients until smooth."),
       ("Serve","Drizzle with oil, serve chilled with injera.")],
      "https://www.youtube.com/watch?v=N9a3JlSfh5s"),

    r("Tegabino",
      "Roasted chickpea flour porridge cooked with spiced butter — a street food favourite.",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      "5 min", "15 min", "2",
      ["1 cup roasted chickpea flour","2 cups water","2 tbsp niter kibbeh","Salt","Berbere to taste"],
      [("Toast flour","Dry-toast chickpea flour in pan 3 min until fragrant."),
       ("Add water","Add water gradually, whisk to avoid lumps."),
       ("Cook","Stir over medium heat 10 min until thick. Add niter kibbeh. Season.")],
      "https://www.youtube.com/watch?v=x4vKwCJ0lq0"),

    r("Alicha Wat",
      "Mild chicken or lamb stew with turmeric, ginger, and garlic — no berbere.",
      "https://images.unsplash.com/photo-1584270354949-56a348646bfe?w=800&q=80",
      "15 min", "50 min", "4",
      ["1kg chicken or lamb pieces","3 onions","1 tsp turmeric","1 tbsp ginger","4 garlic cloves",
       "3 tbsp niter kibbeh","Salt","Injera to serve"],
      [("Cook onions","Cook onions in niter kibbeh 12 min."),
       ("Add spices","Add turmeric, ginger, garlic. Cook 3 min."),
       ("Add meat","Add meat, coat well, cook 35 min until tender. Season.")],
      "https://www.youtube.com/watch?v=vTx7xV2wAXE"),

    r("Bozena Shiro",
      "Shiro wat elevated with chunks of beef or lamb stirred in at the end.",
      "https://images.unsplash.com/photo-1645142601528-1f33f27cc619?w=800&q=80",
      "10 min", "35 min", "4",
      ["1 cup shiro powder","200g beef or lamb, cubed","2 onions","3 tbsp oil",
       "1 tbsp berbere","3 cups water","Salt"],
      [("Brown meat","Sear meat in oil 5 min. Remove."),
       ("Make shiro","Cook onions, add berbere, add water and shiro powder. Simmer 15 min."),
       ("Combine","Return meat to pot, simmer 10 min. Season.")],
      "https://www.youtube.com/watch?v=QI7FJj2j9Js"),

    r("Ful Medames",
      "Mashed fava beans with lemon, garlic, and chilli — popular Ethiopian breakfast.",
      "https://images.unsplash.com/photo-1585707571428-4e211ae03e11?w=800&q=80",
      "5 min", "15 min", "2",
      ["2 cups cooked fava beans","Juice of 1 lemon","2 garlic cloves, minced",
       "1 jalapeño","2 tbsp olive oil","Salt","Injera or bread to serve"],
      [("Mash","Roughly mash fava beans with a fork."),
       ("Season","Add lemon, garlic, jalapeño, oil, salt. Mix well."),
       ("Serve","Serve warm with injera or bread.")],
      "https://www.youtube.com/watch?v=sxhHQp0r-IE"),

    r("Gored Gored",
      "Cubed raw beef tossed with mitmita, awaze, and niter kibbeh — served rare.",
      "https://images.unsplash.com/photo-1568043666682-3baacb822e72?w=800&q=80",
      "15 min", "0 min", "2",
      ["400g very fresh lean beef, cubed","2 tbsp niter kibbeh","1 tsp mitmita",
       "1 tbsp awaze (chilli paste)","Salt"],
      [("Prepare beef","Cube beef into bite-size pieces."),
       ("Toss","Toss with warm niter kibbeh, mitmita, awaze, salt."),
       ("Serve","Serve immediately with injera. Must use very fresh beef.")],
      "https://www.youtube.com/watch?v=OnJiSKzfAWU"),

    r("Kategna",
      "Toasted injera brushed with berbere and niter kibbeh — crispy Ethiopian snack.",
      "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=800&q=80",
      "5 min", "5 min", "2",
      ["2 pieces injera","2 tbsp niter kibbeh","1 tbsp berbere"],
      [("Mix","Stir berbere into melted niter kibbeh."),
       ("Brush","Spread mixture over injera."),
       ("Toast","Grill or pan-toast until crispy edges form. Serve as snack.")],
      "https://www.youtube.com/watch?v=sDhBb1KfAkQ"),

    r("Doro Tibs",
      "Chicken pieces sautéed with onions, rosemary, jalapeño, and awaze sauce.",
      "https://images.unsplash.com/photo-1584270354949-56a348646bfe?w=800&q=80",
      "15 min", "25 min", "3",
      ["600g chicken thighs, boneless","2 onions","2 jalapeños","1 sprig rosemary",
       "2 tbsp niter kibbeh","1 tbsp awaze","Salt"],
      [("Sear chicken","Heat niter kibbeh, sear chicken 5 min per side."),
       ("Add aromatics","Add onions, jalapeños, rosemary. Cook 8 min."),
       ("Finish","Add awaze, toss well. Cook 5 min. Season.")],
      "https://www.youtube.com/watch?v=YZt8JOHzLjE"),

    r("Siga Wat",
      "Beef chunks slow-cooked in a fiery berbere stew with niter kibbeh.",
      "https://images.unsplash.com/photo-1585238341710-4700bde7e3a0?w=800&q=80",
      "15 min", "1 hr 15 min", "4",
      ["700g beef, cubed","4 onions","3 tbsp berbere","3 tbsp niter kibbeh",
       "1 tbsp garlic","1 tsp ginger","Salt"],
      [("Cook onions","Dry-cook onions 15 min, add niter kibbeh, cook 10 min."),
       ("Add berbere","Add berbere, garlic, ginger. Cook 8 min."),
       ("Braise","Add beef, coat well, add 1/2 cup water. Simmer 45 min until tender.")],
      "https://www.youtube.com/watch?v=jhJSzaqgNhE"),

    r("Ye'abesha Gomen",
      "Collard greens braised with onion and spiced butter — classic side dish.",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      "10 min", "30 min", "4",
      ["1 large bunch collard greens","2 onions","3 garlic cloves","2 tbsp niter kibbeh",
       "1/2 tsp turmeric","Salt"],
      [("Prep greens","Remove stems, chop leaves finely."),
       ("Sauté","Cook onions in niter kibbeh 8 min. Add garlic and turmeric."),
       ("Braise","Add greens, stir well, cover and cook 18 min. Season.")],
      "https://www.youtube.com/watch?v=iVqA84WEqyU"),
]

async def seed():
    col = db["recipes"]
    existing = await col.count_documents({})
    if existing > 0:
        print(f"Already have {existing} recipes — dropping and reseeding.")
        await col.drop()
    result = await col.insert_many(RECIPES)
    print(f"Seeded {len(result.inserted_ids)} recipes.")

asyncio.run(seed())
